// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=ts"
// @generated from file example/kanban/task/v1/task.proto (package example.kanban.task.v1, edition 2023)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../../buf/validate/validate_pb.ts";
import type { RecordTimestamps } from "../../../../common/wkt/v1/record_timestamps_pb.ts";
import { file_common_wkt_v1_record_timestamps } from "../../../../common/wkt/v1/record_timestamps_pb.ts";
import { file_google_api_annotations } from "../../../../google/api/annotations_pb.ts";
import { file_protoc_gen_openapiv2_options_annotations } from "../../../../protoc-gen-openapiv2/options/annotations_pb.ts";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file example/kanban/task/v1/task.proto.
 */
export const file_example_kanban_task_v1_task: GenFile = /*@__PURE__*/
  fileDesc("CiFleGFtcGxlL2thbmJhbi90YXNrL3YxL3Rhc2sucHJvdG8SFmV4YW1wbGUua2FuYmFuLnRhc2sudjEiHAoOR2V0VGFza1JlcXVlc3QSCgoCaWQYASABKAkiPQoPR2V0VGFza1Jlc3BvbnNlEioKBHRhc2sYASABKAsyHC5leGFtcGxlLmthbmJhbi50YXNrLnYxLlRhc2sivQEKBFRhc2sSFAoCaWQYASABKAlCCLpIBXIDsAEBEhgKBG5hbWUYAiABKAlCCrpIB3IFEAEYyAESFgoEZGVzYxgDIAEoCUIIukgFcgMYoB8SOAoGc3RhdHVzGAQgASgOMh4uZXhhbXBsZS5rYW5iYW4udGFzay52MS5TdGF0dXNCCLpIBYIBAhABEjMKCnRpbWVzdGFtcHMYBSABKAsyHy5jb21tb24ud2t0LnYxLlJlY29yZFRpbWVzdGFtcHMiVQoRQ3JlYXRlVGFza1JlcXVlc3QSKAoEbmFtZRgBIAEoCUIakkENSgsiWW91ciBUb2RvIrpIB3IFEAEYyAESFgoEZGVzYxgCIAEoCUIIukgFcgMYoB8iSAoSQ3JlYXRlVGFza1Jlc3BvbnNlEjIKBHRhc2sYASABKAsyHC5leGFtcGxlLmthbmJhbi50YXNrLnYxLlRhc2tCBrpIA8gBASpPCgZTdGF0dXMSCwoHQkFDS0xPRxAAEgkKBVJFQURZEAESCQoFRE9JTkcQAhIKCgZSRVZJRVcQAxIICgRET05FEAQSDAoIQVJDSElWRUQQBTKcAgoLVGFza1NlcnZpY2USiAEKCkNyZWF0ZVRhc2sSKS5leGFtcGxlLmthbmJhbi50YXNrLnYxLkNyZWF0ZVRhc2tSZXF1ZXN0GiouZXhhbXBsZS5rYW5iYW4udGFzay52MS5DcmVhdGVUYXNrUmVzcG9uc2UiI4LT5JMCHToBKiIYL2V4YW1wbGUva2FuYmFuL3YxL3Rhc2tzEoEBCgdHZXRUYXNrEiYuZXhhbXBsZS5rYW5iYW4udGFzay52MS5HZXRUYXNrUmVxdWVzdBonLmV4YW1wbGUua2FuYmFuLnRhc2sudjEuR2V0VGFza1Jlc3BvbnNlIiWC0+STAh8SHS9leGFtcGxlL2thbmJhbi92MS90YXNrcy97aWR9Qm8KLGNvbS5iZXRhcmVkdWNlZC5wcm90by5leGFtcGxlLmthbmJhbi50YXNrLnYxUAFaPWdpdGh1Yi5jb20vYmV0YXJlZHVjZWQvcHJvdG8vZ28vZXhhbXBsZS9rYW5iYW4vdGFzay92MTt0YXNrcGJiCGVkaXRpb25zcOgH", [file_buf_validate_validate, file_common_wkt_v1_record_timestamps, file_google_api_annotations, file_protoc_gen_openapiv2_options_annotations]);

/**
 * @generated from message example.kanban.task.v1.GetTaskRequest
 */
export type GetTaskRequest = Message<"example.kanban.task.v1.GetTaskRequest"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;
};

/**
 * Describes the message example.kanban.task.v1.GetTaskRequest.
 * Use `create(GetTaskRequestSchema)` to create a new message.
 */
export const GetTaskRequestSchema: GenMessage<GetTaskRequest> = /*@__PURE__*/
  messageDesc(file_example_kanban_task_v1_task, 0);

/**
 * @generated from message example.kanban.task.v1.GetTaskResponse
 */
export type GetTaskResponse = Message<"example.kanban.task.v1.GetTaskResponse"> & {
  /**
   * @generated from field: example.kanban.task.v1.Task task = 1;
   */
  task?: Task;
};

/**
 * Describes the message example.kanban.task.v1.GetTaskResponse.
 * Use `create(GetTaskResponseSchema)` to create a new message.
 */
export const GetTaskResponseSchema: GenMessage<GetTaskResponse> = /*@__PURE__*/
  messageDesc(file_example_kanban_task_v1_task, 1);

/**
 * @generated from message example.kanban.task.v1.Task
 */
export type Task = Message<"example.kanban.task.v1.Task"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string desc = 3;
   */
  desc: string;

  /**
   * @generated from field: example.kanban.task.v1.Status status = 4;
   */
  status: Status;

  /**
   * @generated from field: common.wkt.v1.RecordTimestamps timestamps = 5;
   */
  timestamps?: RecordTimestamps;
};

/**
 * Describes the message example.kanban.task.v1.Task.
 * Use `create(TaskSchema)` to create a new message.
 */
export const TaskSchema: GenMessage<Task> = /*@__PURE__*/
  messageDesc(file_example_kanban_task_v1_task, 2);

/**
 * @generated from message example.kanban.task.v1.CreateTaskRequest
 */
export type CreateTaskRequest = Message<"example.kanban.task.v1.CreateTaskRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string desc = 2;
   */
  desc: string;
};

/**
 * Describes the message example.kanban.task.v1.CreateTaskRequest.
 * Use `create(CreateTaskRequestSchema)` to create a new message.
 */
export const CreateTaskRequestSchema: GenMessage<CreateTaskRequest> = /*@__PURE__*/
  messageDesc(file_example_kanban_task_v1_task, 3);

/**
 * @generated from message example.kanban.task.v1.CreateTaskResponse
 */
export type CreateTaskResponse = Message<"example.kanban.task.v1.CreateTaskResponse"> & {
  /**
   * @generated from field: example.kanban.task.v1.Task task = 1;
   */
  task?: Task;
};

/**
 * Describes the message example.kanban.task.v1.CreateTaskResponse.
 * Use `create(CreateTaskResponseSchema)` to create a new message.
 */
export const CreateTaskResponseSchema: GenMessage<CreateTaskResponse> = /*@__PURE__*/
  messageDesc(file_example_kanban_task_v1_task, 4);

/**
 * @generated from enum example.kanban.task.v1.Status
 */
export enum Status {
  /**
   * @generated from enum value: BACKLOG = 0;
   */
  BACKLOG = 0,

  /**
   * @generated from enum value: READY = 1;
   */
  READY = 1,

  /**
   * @generated from enum value: DOING = 2;
   */
  DOING = 2,

  /**
   * @generated from enum value: REVIEW = 3;
   */
  REVIEW = 3,

  /**
   * @generated from enum value: DONE = 4;
   */
  DONE = 4,

  /**
   * @generated from enum value: ARCHIVED = 5;
   */
  ARCHIVED = 5,
}

/**
 * Describes the enum example.kanban.task.v1.Status.
 */
export const StatusSchema: GenEnum<Status> = /*@__PURE__*/
  enumDesc(file_example_kanban_task_v1_task, 0);

/**
 * @generated from service example.kanban.task.v1.TaskService
 */
export const TaskService: GenService<{
  /**
   * @generated from rpc example.kanban.task.v1.TaskService.CreateTask
   */
  createTask: {
    methodKind: "unary";
    input: typeof CreateTaskRequestSchema;
    output: typeof CreateTaskResponseSchema;
  },
  /**
   * @generated from rpc example.kanban.task.v1.TaskService.GetTask
   */
  getTask: {
    methodKind: "unary";
    input: typeof GetTaskRequestSchema;
    output: typeof GetTaskResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_example_kanban_task_v1_task, 0);

