// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=ts"
// @generated from file example/kanban/task/v1/task.proto (package example.kanban.task.v1, edition 2023)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage, GenService } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc, serviceDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../../buf/validate/validate_pb.ts";
import type { RecordTimestamps } from "../../../../common/wkt/v1/record_timestamps_pb.ts";
import { file_common_wkt_v1_record_timestamps } from "../../../../common/wkt/v1/record_timestamps_pb.ts";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file example/kanban/task/v1/task.proto.
 */
export const file_example_kanban_task_v1_task: GenFile = /*@__PURE__*/
  fileDesc("CiFleGFtcGxlL2thbmJhbi90YXNrL3YxL3Rhc2sucHJvdG8SFmV4YW1wbGUua2FuYmFuLnRhc2sudjEivQEKBFRhc2sSFAoCaWQYASABKAlCCLpIBXIDsAEBEhgKBG5hbWUYAiABKAlCCrpIB3IFEAEYyAESFgoEZGVzYxgDIAEoCUIIukgFcgMYoB8SOAoGc3RhdHVzGAQgASgOMh4uZXhhbXBsZS5rYW5iYW4udGFzay52MS5TdGF0dXNCCLpIBYIBAhABEjMKCnRpbWVzdGFtcHMYBSABKAsyHy5jb21tb24ud2t0LnYxLlJlY29yZFRpbWVzdGFtcHMiRQoRQ3JlYXRlVGFza1JlcXVlc3QSGAoEbmFtZRgBIAEoCUIKukgHcgUQARjIARIWCgRkZXNjGAIgASgJQgi6SAVyAxigHyJIChJDcmVhdGVUYXNrUmVzcG9uc2USMgoEdGFzaxgBIAEoCzIcLmV4YW1wbGUua2FuYmFuLnRhc2sudjEuVGFza0IGukgDyAEBKk8KBlN0YXR1cxILCgdCQUNLTE9HEAASCQoFUkVBRFkQARIJCgVET0lORxACEgoKBlJFVklFVxADEggKBERPTkUQBBIMCghBUkNISVZFRBAFMnIKC1Rhc2tTZXJ2aWNlEmMKCkNyZWF0ZVRhc2sSKS5leGFtcGxlLmthbmJhbi50YXNrLnYxLkNyZWF0ZVRhc2tSZXF1ZXN0GiouZXhhbXBsZS5rYW5iYW4udGFzay52MS5DcmVhdGVUYXNrUmVzcG9uc2VCbwosY29tLmJldGFyZWR1Y2VkLnByb3RvLmV4YW1wbGUua2FuYmFuLnRhc2sudjFQAVo9Z2l0aHViLmNvbS9iZXRhcmVkdWNlZC9wcm90by9nby9leGFtcGxlL2thbmJhbi90YXNrL3YxO3Rhc2twYmIIZWRpdGlvbnNw6Ac", [file_buf_validate_validate, file_common_wkt_v1_record_timestamps]);

/**
 * @generated from message example.kanban.task.v1.Task
 */
export type Task = Message<"example.kanban.task.v1.Task"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string desc = 3;
   */
  desc: string;

  /**
   * @generated from field: example.kanban.task.v1.Status status = 4;
   */
  status: Status;

  /**
   * @generated from field: common.wkt.v1.RecordTimestamps timestamps = 5;
   */
  timestamps?: RecordTimestamps;
};

/**
 * Describes the message example.kanban.task.v1.Task.
 * Use `create(TaskSchema)` to create a new message.
 */
export const TaskSchema: GenMessage<Task> = /*@__PURE__*/
  messageDesc(file_example_kanban_task_v1_task, 0);

/**
 * @generated from message example.kanban.task.v1.CreateTaskRequest
 */
export type CreateTaskRequest = Message<"example.kanban.task.v1.CreateTaskRequest"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string desc = 2;
   */
  desc: string;
};

/**
 * Describes the message example.kanban.task.v1.CreateTaskRequest.
 * Use `create(CreateTaskRequestSchema)` to create a new message.
 */
export const CreateTaskRequestSchema: GenMessage<CreateTaskRequest> = /*@__PURE__*/
  messageDesc(file_example_kanban_task_v1_task, 1);

/**
 * @generated from message example.kanban.task.v1.CreateTaskResponse
 */
export type CreateTaskResponse = Message<"example.kanban.task.v1.CreateTaskResponse"> & {
  /**
   * @generated from field: example.kanban.task.v1.Task task = 1;
   */
  task?: Task;
};

/**
 * Describes the message example.kanban.task.v1.CreateTaskResponse.
 * Use `create(CreateTaskResponseSchema)` to create a new message.
 */
export const CreateTaskResponseSchema: GenMessage<CreateTaskResponse> = /*@__PURE__*/
  messageDesc(file_example_kanban_task_v1_task, 2);

/**
 * @generated from enum example.kanban.task.v1.Status
 */
export enum Status {
  /**
   * @generated from enum value: BACKLOG = 0;
   */
  BACKLOG = 0,

  /**
   * @generated from enum value: READY = 1;
   */
  READY = 1,

  /**
   * @generated from enum value: DOING = 2;
   */
  DOING = 2,

  /**
   * @generated from enum value: REVIEW = 3;
   */
  REVIEW = 3,

  /**
   * @generated from enum value: DONE = 4;
   */
  DONE = 4,

  /**
   * @generated from enum value: ARCHIVED = 5;
   */
  ARCHIVED = 5,
}

/**
 * Describes the enum example.kanban.task.v1.Status.
 */
export const StatusSchema: GenEnum<Status> = /*@__PURE__*/
  enumDesc(file_example_kanban_task_v1_task, 0);

/**
 * @generated from service example.kanban.task.v1.TaskService
 */
export const TaskService: GenService<{
  /**
   * @generated from rpc example.kanban.task.v1.TaskService.CreateTask
   */
  createTask: {
    methodKind: "unary";
    input: typeof CreateTaskRequestSchema;
    output: typeof CreateTaskResponseSchema;
  },
}> = /*@__PURE__*/
  serviceDesc(file_example_kanban_task_v1_task, 0);

