// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: common/wkt/v1/record_timestamps.proto

package wktpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RecordTimestamps struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=created_at,json=createdAt" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=updated_at,json=updatedAt" json:"updated_at,omitempty"`
	DeletedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=deleted_at,json=deletedAt" json:"deleted_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RecordTimestamps) Reset() {
	*x = RecordTimestamps{}
	mi := &file_common_wkt_v1_record_timestamps_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RecordTimestamps) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RecordTimestamps) ProtoMessage() {}

func (x *RecordTimestamps) ProtoReflect() protoreflect.Message {
	mi := &file_common_wkt_v1_record_timestamps_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RecordTimestamps.ProtoReflect.Descriptor instead.
func (*RecordTimestamps) Descriptor() ([]byte, []int) {
	return file_common_wkt_v1_record_timestamps_proto_rawDescGZIP(), []int{0}
}

func (x *RecordTimestamps) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *RecordTimestamps) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *RecordTimestamps) GetDeletedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.DeletedAt
	}
	return nil
}

var File_common_wkt_v1_record_timestamps_proto protoreflect.FileDescriptor

const file_common_wkt_v1_record_timestamps_proto_rawDesc = "" +
	"\n" +
	"%common/wkt/v1/record_timestamps.proto\x12\rcommon.wkt.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xc3\x01\n" +
	"\x10RecordTimestamps\x129\n" +
	"\n" +
	"created_at\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x129\n" +
	"\n" +
	"deleted_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tdeletedAtB5Z3github.com/betareduced/proto/go/common/wkt/v1;wktpbb\beditionsp\xe8\a"

var (
	file_common_wkt_v1_record_timestamps_proto_rawDescOnce sync.Once
	file_common_wkt_v1_record_timestamps_proto_rawDescData []byte
)

func file_common_wkt_v1_record_timestamps_proto_rawDescGZIP() []byte {
	file_common_wkt_v1_record_timestamps_proto_rawDescOnce.Do(func() {
		file_common_wkt_v1_record_timestamps_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_wkt_v1_record_timestamps_proto_rawDesc), len(file_common_wkt_v1_record_timestamps_proto_rawDesc)))
	})
	return file_common_wkt_v1_record_timestamps_proto_rawDescData
}

var file_common_wkt_v1_record_timestamps_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_common_wkt_v1_record_timestamps_proto_goTypes = []any{
	(*RecordTimestamps)(nil),      // 0: common.wkt.v1.RecordTimestamps
	(*timestamppb.Timestamp)(nil), // 1: google.protobuf.Timestamp
}
var file_common_wkt_v1_record_timestamps_proto_depIdxs = []int32{
	1, // 0: common.wkt.v1.RecordTimestamps.created_at:type_name -> google.protobuf.Timestamp
	1, // 1: common.wkt.v1.RecordTimestamps.updated_at:type_name -> google.protobuf.Timestamp
	1, // 2: common.wkt.v1.RecordTimestamps.deleted_at:type_name -> google.protobuf.Timestamp
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_common_wkt_v1_record_timestamps_proto_init() }
func file_common_wkt_v1_record_timestamps_proto_init() {
	if File_common_wkt_v1_record_timestamps_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_wkt_v1_record_timestamps_proto_rawDesc), len(file_common_wkt_v1_record_timestamps_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_wkt_v1_record_timestamps_proto_goTypes,
		DependencyIndexes: file_common_wkt_v1_record_timestamps_proto_depIdxs,
		MessageInfos:      file_common_wkt_v1_record_timestamps_proto_msgTypes,
	}.Build()
	File_common_wkt_v1_record_timestamps_proto = out.File
	file_common_wkt_v1_record_timestamps_proto_goTypes = nil
	file_common_wkt_v1_record_timestamps_proto_depIdxs = nil
}
