// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: example/kanban/task/v1/task.proto

package taskpb

import (
	v1 "github.com/betareduced/proto/go/common/wkt/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Status int32

const (
	Status_BACKLOG  Status = 0
	Status_READY    Status = 1
	Status_DOING    Status = 2
	Status_REVIEW   Status = 3
	Status_DONE     Status = 4
	Status_ARCHIVED Status = 5
)

// Enum value maps for Status.
var (
	Status_name = map[int32]string{
		0: "BACKLOG",
		1: "READY",
		2: "DOING",
		3: "REVIEW",
		4: "DONE",
		5: "ARCHIVED",
	}
	Status_value = map[string]int32{
		"BACKLOG":  0,
		"READY":    1,
		"DOING":    2,
		"REVIEW":   3,
		"DONE":     4,
		"ARCHIVED": 5,
	}
)

func (x Status) Enum() *Status {
	p := new(Status)
	*p = x
	return p
}

func (x Status) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Status) Descriptor() protoreflect.EnumDescriptor {
	return file_example_kanban_task_v1_task_proto_enumTypes[0].Descriptor()
}

func (Status) Type() protoreflect.EnumType {
	return &file_example_kanban_task_v1_task_proto_enumTypes[0]
}

func (x Status) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Status.Descriptor instead.
func (Status) EnumDescriptor() ([]byte, []int) {
	return file_example_kanban_task_v1_task_proto_rawDescGZIP(), []int{0}
}

type Task struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            *string                `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Name          *string                `protobuf:"bytes,2,opt,name=name" json:"name,omitempty"`
	Desc          *string                `protobuf:"bytes,3,opt,name=desc" json:"desc,omitempty"`
	Status        *Status                `protobuf:"varint,4,opt,name=status,enum=example.kanban.task.v1.Status" json:"status,omitempty"`
	Timestamps    *v1.RecordTimestamps   `protobuf:"bytes,5,opt,name=timestamps" json:"timestamps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Task) Reset() {
	*x = Task{}
	mi := &file_example_kanban_task_v1_task_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Task) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Task) ProtoMessage() {}

func (x *Task) ProtoReflect() protoreflect.Message {
	mi := &file_example_kanban_task_v1_task_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Task.ProtoReflect.Descriptor instead.
func (*Task) Descriptor() ([]byte, []int) {
	return file_example_kanban_task_v1_task_proto_rawDescGZIP(), []int{0}
}

func (x *Task) GetId() string {
	if x != nil && x.Id != nil {
		return *x.Id
	}
	return ""
}

func (x *Task) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *Task) GetDesc() string {
	if x != nil && x.Desc != nil {
		return *x.Desc
	}
	return ""
}

func (x *Task) GetStatus() Status {
	if x != nil && x.Status != nil {
		return *x.Status
	}
	return Status_BACKLOG
}

func (x *Task) GetTimestamps() *v1.RecordTimestamps {
	if x != nil {
		return x.Timestamps
	}
	return nil
}

type CreateTaskRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          *string                `protobuf:"bytes,1,opt,name=name" json:"name,omitempty"`
	Desc          *string                `protobuf:"bytes,2,opt,name=desc" json:"desc,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskRequest) Reset() {
	*x = CreateTaskRequest{}
	mi := &file_example_kanban_task_v1_task_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskRequest) ProtoMessage() {}

func (x *CreateTaskRequest) ProtoReflect() protoreflect.Message {
	mi := &file_example_kanban_task_v1_task_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskRequest.ProtoReflect.Descriptor instead.
func (*CreateTaskRequest) Descriptor() ([]byte, []int) {
	return file_example_kanban_task_v1_task_proto_rawDescGZIP(), []int{1}
}

func (x *CreateTaskRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *CreateTaskRequest) GetDesc() string {
	if x != nil && x.Desc != nil {
		return *x.Desc
	}
	return ""
}

type CreateTaskResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Task          *Task                  `protobuf:"bytes,1,opt,name=task" json:"task,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateTaskResponse) Reset() {
	*x = CreateTaskResponse{}
	mi := &file_example_kanban_task_v1_task_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateTaskResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateTaskResponse) ProtoMessage() {}

func (x *CreateTaskResponse) ProtoReflect() protoreflect.Message {
	mi := &file_example_kanban_task_v1_task_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateTaskResponse.ProtoReflect.Descriptor instead.
func (*CreateTaskResponse) Descriptor() ([]byte, []int) {
	return file_example_kanban_task_v1_task_proto_rawDescGZIP(), []int{2}
}

func (x *CreateTaskResponse) GetTask() *Task {
	if x != nil {
		return x.Task
	}
	return nil
}

var File_example_kanban_task_v1_task_proto protoreflect.FileDescriptor

const file_example_kanban_task_v1_task_proto_rawDesc = "" +
	"\n" +
	"!example/kanban/task/v1/task.proto\x12\x16example.kanban.task.v1\x1a%common/wkt/v1/record_timestamps.proto\"\xb7\x01\n" +
	"\x04Task\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x03 \x01(\tR\x04desc\x126\n" +
	"\x06status\x18\x04 \x01(\x0e2\x1e.example.kanban.task.v1.StatusR\x06status\x12?\n" +
	"\n" +
	"timestamps\x18\x05 \x01(\v2\x1f.common.wkt.v1.RecordTimestampsR\n" +
	"timestamps\";\n" +
	"\x11CreateTaskRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04desc\x18\x02 \x01(\tR\x04desc\"F\n" +
	"\x12CreateTaskResponse\x120\n" +
	"\x04task\x18\x01 \x01(\v2\x1c.example.kanban.task.v1.TaskR\x04task*O\n" +
	"\x06Status\x12\v\n" +
	"\aBACKLOG\x10\x00\x12\t\n" +
	"\x05READY\x10\x01\x12\t\n" +
	"\x05DOING\x10\x02\x12\n" +
	"\n" +
	"\x06REVIEW\x10\x03\x12\b\n" +
	"\x04DONE\x10\x04\x12\f\n" +
	"\bARCHIVED\x10\x052r\n" +
	"\vTaskService\x12c\n" +
	"\n" +
	"CreateTask\x12).example.kanban.task.v1.CreateTaskRequest\x1a*.example.kanban.task.v1.CreateTaskResponseB?Z=github.com/betareduced/proto/go/example/kanban/task/v1;taskpbb\beditionsp\xe8\a"

var (
	file_example_kanban_task_v1_task_proto_rawDescOnce sync.Once
	file_example_kanban_task_v1_task_proto_rawDescData []byte
)

func file_example_kanban_task_v1_task_proto_rawDescGZIP() []byte {
	file_example_kanban_task_v1_task_proto_rawDescOnce.Do(func() {
		file_example_kanban_task_v1_task_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_example_kanban_task_v1_task_proto_rawDesc), len(file_example_kanban_task_v1_task_proto_rawDesc)))
	})
	return file_example_kanban_task_v1_task_proto_rawDescData
}

var file_example_kanban_task_v1_task_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_example_kanban_task_v1_task_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_example_kanban_task_v1_task_proto_goTypes = []any{
	(Status)(0),                 // 0: example.kanban.task.v1.Status
	(*Task)(nil),                // 1: example.kanban.task.v1.Task
	(*CreateTaskRequest)(nil),   // 2: example.kanban.task.v1.CreateTaskRequest
	(*CreateTaskResponse)(nil),  // 3: example.kanban.task.v1.CreateTaskResponse
	(*v1.RecordTimestamps)(nil), // 4: common.wkt.v1.RecordTimestamps
}
var file_example_kanban_task_v1_task_proto_depIdxs = []int32{
	0, // 0: example.kanban.task.v1.Task.status:type_name -> example.kanban.task.v1.Status
	4, // 1: example.kanban.task.v1.Task.timestamps:type_name -> common.wkt.v1.RecordTimestamps
	1, // 2: example.kanban.task.v1.CreateTaskResponse.task:type_name -> example.kanban.task.v1.Task
	2, // 3: example.kanban.task.v1.TaskService.CreateTask:input_type -> example.kanban.task.v1.CreateTaskRequest
	3, // 4: example.kanban.task.v1.TaskService.CreateTask:output_type -> example.kanban.task.v1.CreateTaskResponse
	4, // [4:5] is the sub-list for method output_type
	3, // [3:4] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_example_kanban_task_v1_task_proto_init() }
func file_example_kanban_task_v1_task_proto_init() {
	if File_example_kanban_task_v1_task_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_example_kanban_task_v1_task_proto_rawDesc), len(file_example_kanban_task_v1_task_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_example_kanban_task_v1_task_proto_goTypes,
		DependencyIndexes: file_example_kanban_task_v1_task_proto_depIdxs,
		EnumInfos:         file_example_kanban_task_v1_task_proto_enumTypes,
		MessageInfos:      file_example_kanban_task_v1_task_proto_msgTypes,
	}.Build()
	File_example_kanban_task_v1_task_proto = out.File
	file_example_kanban_task_v1_task_proto_goTypes = nil
	file_example_kanban_task_v1_task_proto_depIdxs = nil
}
