// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: common/wkt/v1/record_timestamps.proto
// Protobuf Java Version: 4.34.1

package com.betareduced.proto.common.wkt.v1;

@com.google.protobuf.Generated
public final class RecordTimestampsOuterClass extends com.google.protobuf.GeneratedFile {
  private RecordTimestampsOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "RecordTimestampsOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_common_wkt_v1_RecordTimestamps_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_common_wkt_v1_RecordTimestamps_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n%common/wkt/v1/record_timestamps.proto\022" +
      "\rcommon.wkt.v1\032\037google/protobuf/timestam" +
      "p.proto\"\303\001\n\020RecordTimestamps\0229\n\ncreated_" +
      "at\030\001 \001(\0132\032.google.protobuf.TimestampR\tcr" +
      "eatedAt\0229\n\nupdated_at\030\002 \001(\0132\032.google.pro" +
      "tobuf.TimestampR\tupdatedAt\0229\n\ndeleted_at" +
      "\030\003 \001(\0132\032.google.protobuf.TimestampR\tdele" +
      "tedAtB\\\n#com.betareduced.proto.common.wk" +
      "t.v1P\001Z3github.com/betareduced/proto/go/" +
      "common/wkt/v1;wktpbb\010editionsp\350\007"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_common_wkt_v1_RecordTimestamps_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_common_wkt_v1_RecordTimestamps_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_common_wkt_v1_RecordTimestamps_descriptor,
        new java.lang.String[] { "CreatedAt", "UpdatedAt", "DeletedAt", });
    descriptor.resolveAllFeaturesImmutable();
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
