// @generated by protoc-gen-es v2.11.0 with parameter "target=ts,import_extension=ts"
// @generated from file common/wkt/v1/record_timestamps.proto (package common.wkt.v1, edition 2023)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "@bufbuild/protobuf/wkt";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file common/wkt/v1/record_timestamps.proto.
 */
export const file_common_wkt_v1_record_timestamps: GenFile = /*@__PURE__*/
  fileDesc("CiVjb21tb24vd2t0L3YxL3JlY29yZF90aW1lc3RhbXBzLnByb3RvEg1jb21tb24ud2t0LnYxIqIBChBSZWNvcmRUaW1lc3RhbXBzEi4KCmNyZWF0ZWRfYXQYASABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi4KCnVwZGF0ZWRfYXQYAiABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi4KCmRlbGV0ZWRfYXQYAyABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wQlwKI2NvbS5iZXRhcmVkdWNlZC5wcm90by5jb21tb24ud2t0LnYxUAFaM2dpdGh1Yi5jb20vYmV0YXJlZHVjZWQvcHJvdG8vZ28vY29tbW9uL3drdC92MTt3a3RwYmIIZWRpdGlvbnNw6Ac", [file_google_protobuf_timestamp]);

/**
 * @generated from message common.wkt.v1.RecordTimestamps
 */
export type RecordTimestamps = Message<"common.wkt.v1.RecordTimestamps"> & {
  /**
   * @generated from field: google.protobuf.Timestamp created_at = 1;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp updated_at = 2;
   */
  updatedAt?: Timestamp;

  /**
   * @generated from field: google.protobuf.Timestamp deleted_at = 3;
   */
  deletedAt?: Timestamp;
};

/**
 * Describes the message common.wkt.v1.RecordTimestamps.
 * Use `create(RecordTimestampsSchema)` to create a new message.
 */
export const RecordTimestampsSchema: GenMessage<RecordTimestamps> = /*@__PURE__*/
  messageDesc(file_common_wkt_v1_record_timestamps, 0);

