// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: example/kanban/task/v1/task.proto
// Protobuf Java Version: 4.34.1

package com.betareduced.proto.example.kanban.task.v1;

@com.google.protobuf.Generated
public interface CreateTaskRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:example.kanban.task.v1.CreateTaskRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return Whether the name field is set.
   */
  boolean hasName();
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The name.
   */
  java.lang.String getName();
  /**
   * <code>string name = 1 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>string desc = 2 [json_name = "desc"];</code>
   * @return Whether the desc field is set.
   */
  boolean hasDesc();
  /**
   * <code>string desc = 2 [json_name = "desc"];</code>
   * @return The desc.
   */
  java.lang.String getDesc();
  /**
   * <code>string desc = 2 [json_name = "desc"];</code>
   * @return The bytes for desc.
   */
  com.google.protobuf.ByteString
      getDescBytes();
}
