// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: example/kanban/task/v1/task.proto
// Protobuf Java Version: 4.34.1

package com.betareduced.proto.example.kanban.task.v1;

@com.google.protobuf.Generated
public interface CreateTaskResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:example.kanban.task.v1.CreateTaskResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.example.kanban.task.v1.Task task = 1 [json_name = "task", (.buf.validate.field) = { ... }</code>
   * @return Whether the task field is set.
   */
  boolean hasTask();
  /**
   * <code>.example.kanban.task.v1.Task task = 1 [json_name = "task", (.buf.validate.field) = { ... }</code>
   * @return The task.
   */
  com.betareduced.proto.example.kanban.task.v1.Task getTask();
  /**
   * <code>.example.kanban.task.v1.Task task = 1 [json_name = "task", (.buf.validate.field) = { ... }</code>
   */
  com.betareduced.proto.example.kanban.task.v1.TaskOrBuilder getTaskOrBuilder();
}
