// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: example/kanban/task/v1/task.proto
// Protobuf Java Version: 4.34.1

package com.betareduced.proto.example.kanban.task.v1;

@com.google.protobuf.Generated
public interface GetTaskResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:example.kanban.task.v1.GetTaskResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.example.kanban.task.v1.Task task = 1 [json_name = "task"];</code>
   * @return Whether the task field is set.
   */
  boolean hasTask();
  /**
   * <code>.example.kanban.task.v1.Task task = 1 [json_name = "task"];</code>
   * @return The task.
   */
  com.betareduced.proto.example.kanban.task.v1.Task getTask();
  /**
   * <code>.example.kanban.task.v1.Task task = 1 [json_name = "task"];</code>
   */
  com.betareduced.proto.example.kanban.task.v1.TaskOrBuilder getTaskOrBuilder();
}
