// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: example/kanban/task/v1/task.proto
// Protobuf Java Version: 4.34.1

package com.betareduced.proto.example.kanban.task.v1;

/**
 * Protobuf type {@code example.kanban.task.v1.ListTaskRequest}
 */
@com.google.protobuf.Generated
public final class ListTaskRequest extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:example.kanban.task.v1.ListTaskRequest)
    ListTaskRequestOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "ListTaskRequest");
  }
  // Use ListTaskRequest.newBuilder() to construct.
  private ListTaskRequest(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ListTaskRequest() {
    sortBy_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.betareduced.proto.example.kanban.task.v1.TaskOuterClass.internal_static_example_kanban_task_v1_ListTaskRequest_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.betareduced.proto.example.kanban.task.v1.TaskOuterClass.internal_static_example_kanban_task_v1_ListTaskRequest_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.betareduced.proto.example.kanban.task.v1.TaskOuterClass.internal_static_example_kanban_task_v1_ListTaskRequest_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.class, com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Builder.class);
  }

  /**
   * Protobuf enum {@code example.kanban.task.v1.ListTaskRequest.Sortkey}
   */
  public enum Sortkey
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>CREATED_AT_ASC = 0;</code>
     */
    CREATED_AT_ASC(0),
    /**
     * <code>CREATED_AT_DESC = 1;</code>
     */
    CREATED_AT_DESC(1),
    /**
     * <code>UPDATED_AT_ASC = 2;</code>
     */
    UPDATED_AT_ASC(2),
    /**
     * <code>UPDATED_AT_DESC = 3;</code>
     */
    UPDATED_AT_DESC(3),
    UNRECOGNIZED(-1),
    ;

    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 34,
        /* patch= */ 1,
        /* suffix= */ "",
        "Sortkey");
    }
    /**
     * <code>CREATED_AT_ASC = 0;</code>
     */
    public static final int CREATED_AT_ASC_VALUE = 0;
    /**
     * <code>CREATED_AT_DESC = 1;</code>
     */
    public static final int CREATED_AT_DESC_VALUE = 1;
    /**
     * <code>UPDATED_AT_ASC = 2;</code>
     */
    public static final int UPDATED_AT_ASC_VALUE = 2;
    /**
     * <code>UPDATED_AT_DESC = 3;</code>
     */
    public static final int UPDATED_AT_DESC_VALUE = 3;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Sortkey valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Sortkey forNumber(int value) {
      switch (value) {
        case 0: return CREATED_AT_ASC;
        case 1: return CREATED_AT_DESC;
        case 2: return UPDATED_AT_ASC;
        case 3: return UPDATED_AT_DESC;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Sortkey>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Sortkey> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Sortkey>() {
            public Sortkey findValueByNumber(int number) {
              return Sortkey.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValue(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.getDescriptor().getEnumType(0);
    }

    private static final Sortkey[] VALUES = values();

    public static Sortkey valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Sortkey(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:example.kanban.task.v1.ListTaskRequest.Sortkey)
  }

  public interface FilterOrBuilder extends
      // @@protoc_insertion_point(interface_extends:example.kanban.task.v1.ListTaskRequest.Filter)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.example.kanban.task.v1.Status status = 1 [json_name = "status"];</code>
     * @return Whether the status field is set.
     */
    boolean hasStatus();
    /**
     * <code>.example.kanban.task.v1.Status status = 1 [json_name = "status"];</code>
     * @return The enum numeric value on the wire for status.
     */
    int getStatusValue();
    /**
     * <code>.example.kanban.task.v1.Status status = 1 [json_name = "status"];</code>
     * @return The status.
     */
    com.betareduced.proto.example.kanban.task.v1.Status getStatus();
  }
  /**
   * Protobuf type {@code example.kanban.task.v1.ListTaskRequest.Filter}
   */
  public static final class Filter extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:example.kanban.task.v1.ListTaskRequest.Filter)
      FilterOrBuilder {
  private static final long serialVersionUID = 0L;
    static {
      com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
        com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
        /* major= */ 4,
        /* minor= */ 34,
        /* patch= */ 1,
        /* suffix= */ "",
        "Filter");
    }
    // Use Filter.newBuilder() to construct.
    private Filter(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
    }
    private Filter() {
      status_ = 0;
    }

    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.betareduced.proto.example.kanban.task.v1.TaskOuterClass.internal_static_example_kanban_task_v1_ListTaskRequest_Filter_descriptor;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
      return com.betareduced.proto.example.kanban.task.v1.TaskOuterClass.internal_static_example_kanban_task_v1_ListTaskRequest_Filter_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.betareduced.proto.example.kanban.task.v1.TaskOuterClass.internal_static_example_kanban_task_v1_ListTaskRequest_Filter_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter.class, com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter.Builder.class);
    }

    private int bitField0_;
    public static final int STATUS_FIELD_NUMBER = 1;
    private int status_ = 0;
    /**
     * <code>.example.kanban.task.v1.Status status = 1 [json_name = "status"];</code>
     * @return Whether the status field is set.
     */
    @java.lang.Override public boolean hasStatus() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.example.kanban.task.v1.Status status = 1 [json_name = "status"];</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.example.kanban.task.v1.Status status = 1 [json_name = "status"];</code>
     * @return The status.
     */
    @java.lang.Override public com.betareduced.proto.example.kanban.task.v1.Status getStatus() {
      com.betareduced.proto.example.kanban.task.v1.Status result = com.betareduced.proto.example.kanban.task.v1.Status.forNumber(status_);
      return result == null ? com.betareduced.proto.example.kanban.task.v1.Status.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (((bitField0_ & 0x00000001) != 0)) {
        output.writeEnum(1, status_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) != 0)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, status_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter)) {
        return super.equals(obj);
      }
      com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter other = (com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter) obj;

      if (hasStatus() != other.hasStatus()) return false;
      if (hasStatus()) {
        if (status_ != other.status_) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      if (hasStatus()) {
        hash = (37 * hash) + STATUS_FIELD_NUMBER;
        hash = (53 * hash) + status_;
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    public static com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input);
    }

    public static com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input);
    }
    public static com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessage
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code example.kanban.task.v1.ListTaskRequest.Filter}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:example.kanban.task.v1.ListTaskRequest.Filter)
        com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.FilterOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.betareduced.proto.example.kanban.task.v1.TaskOuterClass.internal_static_example_kanban_task_v1_ListTaskRequest_Filter_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.betareduced.proto.example.kanban.task.v1.TaskOuterClass.internal_static_example_kanban_task_v1_ListTaskRequest_Filter_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter.class, com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter.Builder.class);
      }

      // Construct using com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        bitField0_ = 0;
        status_ = 0;
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.betareduced.proto.example.kanban.task.v1.TaskOuterClass.internal_static_example_kanban_task_v1_ListTaskRequest_Filter_descriptor;
      }

      @java.lang.Override
      public com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter getDefaultInstanceForType() {
        return com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter.getDefaultInstance();
      }

      @java.lang.Override
      public com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter build() {
        com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter buildPartial() {
        com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter result = new com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter(this);
        if (bitField0_ != 0) { buildPartial0(result); }
        onBuilt();
        return result;
      }

      private void buildPartial0(com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter result) {
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) != 0)) {
          result.status_ = status_;
          to_bitField0_ |= 0x00000001;
        }
        result.bitField0_ |= to_bitField0_;
      }

      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter) {
          return mergeFrom((com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter other) {
        if (other == com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter.getDefaultInstance()) return this;
        if (other.hasStatus()) {
          setStatusValue(other.getStatusValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                status_ = input.readEnum();
                bitField0_ |= 0x00000001;
                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }
      private int bitField0_;

      private int status_ = 0;
      /**
       * <code>.example.kanban.task.v1.Status status = 1 [json_name = "status"];</code>
       * @return Whether the status field is set.
       */
      @java.lang.Override public boolean hasStatus() {
        return ((bitField0_ & 0x00000001) != 0);
      }
      /**
       * <code>.example.kanban.task.v1.Status status = 1 [json_name = "status"];</code>
       * @return The enum numeric value on the wire for status.
       */
      @java.lang.Override public int getStatusValue() {
        return status_;
      }
      /**
       * <code>.example.kanban.task.v1.Status status = 1 [json_name = "status"];</code>
       * @param value The enum numeric value on the wire for status to set.
       * @throws IllegalArgumentException if UNRECOGNIZED is provided.
       * @return This builder for chaining.
       */
      public Builder setStatusValue(int value) {
        status_ = value;
        bitField0_ |= 0x00000001;
        onChanged();
        return this;
      }
      /**
       * <code>.example.kanban.task.v1.Status status = 1 [json_name = "status"];</code>
       * @return The status.
       */
      @java.lang.Override
      public com.betareduced.proto.example.kanban.task.v1.Status getStatus() {
        com.betareduced.proto.example.kanban.task.v1.Status result = com.betareduced.proto.example.kanban.task.v1.Status.forNumber(status_);
        return result == null ? com.betareduced.proto.example.kanban.task.v1.Status.UNRECOGNIZED : result;
      }
      /**
       * <code>.example.kanban.task.v1.Status status = 1 [json_name = "status"];</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(com.betareduced.proto.example.kanban.task.v1.Status value) {
        if (value == null) { throw new NullPointerException(); }
        bitField0_ |= 0x00000001;
        status_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.example.kanban.task.v1.Status status = 1 [json_name = "status"];</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        bitField0_ = (bitField0_ & ~0x00000001);
        status_ = 0;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:example.kanban.task.v1.ListTaskRequest.Filter)
    }

    // @@protoc_insertion_point(class_scope:example.kanban.task.v1.ListTaskRequest.Filter)
    private static final com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter();
    }

    public static com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Filter>
        PARSER = new com.google.protobuf.AbstractParser<Filter>() {
      @java.lang.Override
      public Filter parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<Filter> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Filter> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private int bitField0_;
  public static final int F_FIELD_NUMBER = 1;
  private com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter f_;
  /**
   * <code>.example.kanban.task.v1.ListTaskRequest.Filter f = 1 [json_name = "f"];</code>
   * @return Whether the f field is set.
   */
  @java.lang.Override
  public boolean hasF() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>.example.kanban.task.v1.ListTaskRequest.Filter f = 1 [json_name = "f"];</code>
   * @return The f.
   */
  @java.lang.Override
  public com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter getF() {
    return f_ == null ? com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter.getDefaultInstance() : f_;
  }
  /**
   * <code>.example.kanban.task.v1.ListTaskRequest.Filter f = 1 [json_name = "f"];</code>
   */
  @java.lang.Override
  public com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.FilterOrBuilder getFOrBuilder() {
    return f_ == null ? com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter.getDefaultInstance() : f_;
  }

  public static final int SORT_BY_FIELD_NUMBER = 2;
  private int sortBy_ = 0;
  /**
   * <code>.example.kanban.task.v1.ListTaskRequest.Sortkey sort_by = 2 [json_name = "sortBy"];</code>
   * @return Whether the sortBy field is set.
   */
  @java.lang.Override public boolean hasSortBy() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>.example.kanban.task.v1.ListTaskRequest.Sortkey sort_by = 2 [json_name = "sortBy"];</code>
   * @return The enum numeric value on the wire for sortBy.
   */
  @java.lang.Override public int getSortByValue() {
    return sortBy_;
  }
  /**
   * <code>.example.kanban.task.v1.ListTaskRequest.Sortkey sort_by = 2 [json_name = "sortBy"];</code>
   * @return The sortBy.
   */
  @java.lang.Override public com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Sortkey getSortBy() {
    com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Sortkey result = com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Sortkey.forNumber(sortBy_);
    return result == null ? com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Sortkey.UNRECOGNIZED : result;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      output.writeMessage(1, getF());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      output.writeEnum(2, sortBy_);
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getF());
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, sortBy_);
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.betareduced.proto.example.kanban.task.v1.ListTaskRequest)) {
      return super.equals(obj);
    }
    com.betareduced.proto.example.kanban.task.v1.ListTaskRequest other = (com.betareduced.proto.example.kanban.task.v1.ListTaskRequest) obj;

    if (hasF() != other.hasF()) return false;
    if (hasF()) {
      if (!getF()
          .equals(other.getF())) return false;
    }
    if (hasSortBy() != other.hasSortBy()) return false;
    if (hasSortBy()) {
      if (sortBy_ != other.sortBy_) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasF()) {
      hash = (37 * hash) + F_FIELD_NUMBER;
      hash = (53 * hash) + getF().hashCode();
    }
    if (hasSortBy()) {
      hash = (37 * hash) + SORT_BY_FIELD_NUMBER;
      hash = (53 * hash) + sortBy_;
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.betareduced.proto.example.kanban.task.v1.ListTaskRequest parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.betareduced.proto.example.kanban.task.v1.ListTaskRequest parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.betareduced.proto.example.kanban.task.v1.ListTaskRequest parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.betareduced.proto.example.kanban.task.v1.ListTaskRequest parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.betareduced.proto.example.kanban.task.v1.ListTaskRequest parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.betareduced.proto.example.kanban.task.v1.ListTaskRequest parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.betareduced.proto.example.kanban.task.v1.ListTaskRequest parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.betareduced.proto.example.kanban.task.v1.ListTaskRequest parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.betareduced.proto.example.kanban.task.v1.ListTaskRequest parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.betareduced.proto.example.kanban.task.v1.ListTaskRequest parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.betareduced.proto.example.kanban.task.v1.ListTaskRequest parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.betareduced.proto.example.kanban.task.v1.ListTaskRequest parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.betareduced.proto.example.kanban.task.v1.ListTaskRequest prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code example.kanban.task.v1.ListTaskRequest}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:example.kanban.task.v1.ListTaskRequest)
      com.betareduced.proto.example.kanban.task.v1.ListTaskRequestOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.betareduced.proto.example.kanban.task.v1.TaskOuterClass.internal_static_example_kanban_task_v1_ListTaskRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.betareduced.proto.example.kanban.task.v1.TaskOuterClass.internal_static_example_kanban_task_v1_ListTaskRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.class, com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Builder.class);
    }

    // Construct using com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetFFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      f_ = null;
      if (fBuilder_ != null) {
        fBuilder_.dispose();
        fBuilder_ = null;
      }
      sortBy_ = 0;
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.betareduced.proto.example.kanban.task.v1.TaskOuterClass.internal_static_example_kanban_task_v1_ListTaskRequest_descriptor;
    }

    @java.lang.Override
    public com.betareduced.proto.example.kanban.task.v1.ListTaskRequest getDefaultInstanceForType() {
      return com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.getDefaultInstance();
    }

    @java.lang.Override
    public com.betareduced.proto.example.kanban.task.v1.ListTaskRequest build() {
      com.betareduced.proto.example.kanban.task.v1.ListTaskRequest result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.betareduced.proto.example.kanban.task.v1.ListTaskRequest buildPartial() {
      com.betareduced.proto.example.kanban.task.v1.ListTaskRequest result = new com.betareduced.proto.example.kanban.task.v1.ListTaskRequest(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.betareduced.proto.example.kanban.task.v1.ListTaskRequest result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.f_ = fBuilder_ == null
            ? f_
            : fBuilder_.build();
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.sortBy_ = sortBy_;
        to_bitField0_ |= 0x00000002;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.betareduced.proto.example.kanban.task.v1.ListTaskRequest) {
        return mergeFrom((com.betareduced.proto.example.kanban.task.v1.ListTaskRequest)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.betareduced.proto.example.kanban.task.v1.ListTaskRequest other) {
      if (other == com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.getDefaultInstance()) return this;
      if (other.hasF()) {
        mergeF(other.getF());
      }
      if (other.hasSortBy()) {
        setSortByValue(other.getSortByValue());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              input.readMessage(
                  internalGetFFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 16: {
              sortBy_ = input.readEnum();
              bitField0_ |= 0x00000002;
              break;
            } // case 16
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter f_;
    private com.google.protobuf.SingleFieldBuilder<
        com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter, com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter.Builder, com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.FilterOrBuilder> fBuilder_;
    /**
     * <code>.example.kanban.task.v1.ListTaskRequest.Filter f = 1 [json_name = "f"];</code>
     * @return Whether the f field is set.
     */
    public boolean hasF() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>.example.kanban.task.v1.ListTaskRequest.Filter f = 1 [json_name = "f"];</code>
     * @return The f.
     */
    public com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter getF() {
      if (fBuilder_ == null) {
        return f_ == null ? com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter.getDefaultInstance() : f_;
      } else {
        return fBuilder_.getMessage();
      }
    }
    /**
     * <code>.example.kanban.task.v1.ListTaskRequest.Filter f = 1 [json_name = "f"];</code>
     */
    public Builder setF(com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter value) {
      if (fBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        f_ = value;
      } else {
        fBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.example.kanban.task.v1.ListTaskRequest.Filter f = 1 [json_name = "f"];</code>
     */
    public Builder setF(
        com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter.Builder builderForValue) {
      if (fBuilder_ == null) {
        f_ = builderForValue.build();
      } else {
        fBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>.example.kanban.task.v1.ListTaskRequest.Filter f = 1 [json_name = "f"];</code>
     */
    public Builder mergeF(com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter value) {
      if (fBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0) &&
          f_ != null &&
          f_ != com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter.getDefaultInstance()) {
          getFBuilder().mergeFrom(value);
        } else {
          f_ = value;
        }
      } else {
        fBuilder_.mergeFrom(value);
      }
      if (f_ != null) {
        bitField0_ |= 0x00000001;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.example.kanban.task.v1.ListTaskRequest.Filter f = 1 [json_name = "f"];</code>
     */
    public Builder clearF() {
      bitField0_ = (bitField0_ & ~0x00000001);
      f_ = null;
      if (fBuilder_ != null) {
        fBuilder_.dispose();
        fBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.example.kanban.task.v1.ListTaskRequest.Filter f = 1 [json_name = "f"];</code>
     */
    public com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter.Builder getFBuilder() {
      bitField0_ |= 0x00000001;
      onChanged();
      return internalGetFFieldBuilder().getBuilder();
    }
    /**
     * <code>.example.kanban.task.v1.ListTaskRequest.Filter f = 1 [json_name = "f"];</code>
     */
    public com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.FilterOrBuilder getFOrBuilder() {
      if (fBuilder_ != null) {
        return fBuilder_.getMessageOrBuilder();
      } else {
        return f_ == null ?
            com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter.getDefaultInstance() : f_;
      }
    }
    /**
     * <code>.example.kanban.task.v1.ListTaskRequest.Filter f = 1 [json_name = "f"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter, com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter.Builder, com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.FilterOrBuilder> 
        internalGetFFieldBuilder() {
      if (fBuilder_ == null) {
        fBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter, com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter.Builder, com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.FilterOrBuilder>(
                getF(),
                getParentForChildren(),
                isClean());
        f_ = null;
      }
      return fBuilder_;
    }

    private int sortBy_ = 0;
    /**
     * <code>.example.kanban.task.v1.ListTaskRequest.Sortkey sort_by = 2 [json_name = "sortBy"];</code>
     * @return Whether the sortBy field is set.
     */
    @java.lang.Override public boolean hasSortBy() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>.example.kanban.task.v1.ListTaskRequest.Sortkey sort_by = 2 [json_name = "sortBy"];</code>
     * @return The enum numeric value on the wire for sortBy.
     */
    @java.lang.Override public int getSortByValue() {
      return sortBy_;
    }
    /**
     * <code>.example.kanban.task.v1.ListTaskRequest.Sortkey sort_by = 2 [json_name = "sortBy"];</code>
     * @param value The enum numeric value on the wire for sortBy to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setSortByValue(int value) {
      sortBy_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>.example.kanban.task.v1.ListTaskRequest.Sortkey sort_by = 2 [json_name = "sortBy"];</code>
     * @return The sortBy.
     */
    @java.lang.Override
    public com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Sortkey getSortBy() {
      com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Sortkey result = com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Sortkey.forNumber(sortBy_);
      return result == null ? com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Sortkey.UNRECOGNIZED : result;
    }
    /**
     * <code>.example.kanban.task.v1.ListTaskRequest.Sortkey sort_by = 2 [json_name = "sortBy"];</code>
     * @param value The sortBy to set.
     * @return This builder for chaining.
     */
    public Builder setSortBy(com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Sortkey value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000002;
      sortBy_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.example.kanban.task.v1.ListTaskRequest.Sortkey sort_by = 2 [json_name = "sortBy"];</code>
     * @return This builder for chaining.
     */
    public Builder clearSortBy() {
      bitField0_ = (bitField0_ & ~0x00000002);
      sortBy_ = 0;
      onChanged();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:example.kanban.task.v1.ListTaskRequest)
  }

  // @@protoc_insertion_point(class_scope:example.kanban.task.v1.ListTaskRequest)
  private static final com.betareduced.proto.example.kanban.task.v1.ListTaskRequest DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.betareduced.proto.example.kanban.task.v1.ListTaskRequest();
  }

  public static com.betareduced.proto.example.kanban.task.v1.ListTaskRequest getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListTaskRequest>
      PARSER = new com.google.protobuf.AbstractParser<ListTaskRequest>() {
    @java.lang.Override
    public ListTaskRequest parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListTaskRequest> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListTaskRequest> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.betareduced.proto.example.kanban.task.v1.ListTaskRequest getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

