// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: example/kanban/task/v1/task.proto
// Protobuf Java Version: 4.34.1

package com.betareduced.proto.example.kanban.task.v1;

/**
 * Protobuf type {@code example.kanban.task.v1.ListTaskResponse}
 */
@com.google.protobuf.Generated
public final class ListTaskResponse extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:example.kanban.task.v1.ListTaskResponse)
    ListTaskResponseOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "ListTaskResponse");
  }
  // Use ListTaskResponse.newBuilder() to construct.
  private ListTaskResponse(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private ListTaskResponse() {
    content_ = java.util.Collections.emptyList();
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.betareduced.proto.example.kanban.task.v1.TaskOuterClass.internal_static_example_kanban_task_v1_ListTaskResponse_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.betareduced.proto.example.kanban.task.v1.TaskOuterClass.internal_static_example_kanban_task_v1_ListTaskResponse_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.betareduced.proto.example.kanban.task.v1.TaskOuterClass.internal_static_example_kanban_task_v1_ListTaskResponse_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.betareduced.proto.example.kanban.task.v1.ListTaskResponse.class, com.betareduced.proto.example.kanban.task.v1.ListTaskResponse.Builder.class);
  }

  public static final int CONTENT_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private java.util.List<com.betareduced.proto.example.kanban.task.v1.Task> content_;
  /**
   * <code>repeated .example.kanban.task.v1.Task content = 1 [json_name = "content"];</code>
   */
  @java.lang.Override
  public java.util.List<com.betareduced.proto.example.kanban.task.v1.Task> getContentList() {
    return content_;
  }
  /**
   * <code>repeated .example.kanban.task.v1.Task content = 1 [json_name = "content"];</code>
   */
  @java.lang.Override
  public java.util.List<? extends com.betareduced.proto.example.kanban.task.v1.TaskOrBuilder> 
      getContentOrBuilderList() {
    return content_;
  }
  /**
   * <code>repeated .example.kanban.task.v1.Task content = 1 [json_name = "content"];</code>
   */
  @java.lang.Override
  public int getContentCount() {
    return content_.size();
  }
  /**
   * <code>repeated .example.kanban.task.v1.Task content = 1 [json_name = "content"];</code>
   */
  @java.lang.Override
  public com.betareduced.proto.example.kanban.task.v1.Task getContent(int index) {
    return content_.get(index);
  }
  /**
   * <code>repeated .example.kanban.task.v1.Task content = 1 [json_name = "content"];</code>
   */
  @java.lang.Override
  public com.betareduced.proto.example.kanban.task.v1.TaskOrBuilder getContentOrBuilder(
      int index) {
    return content_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < content_.size(); i++) {
      output.writeMessage(1, content_.get(i));
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;

        {
          final int count = content_.size();
          for (int i = 0; i < count; i++) {
            size += com.google.protobuf.CodedOutputStream
              .computeMessageSizeNoTag(content_.get(i));
          }
          size += 1 * count;
        }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.betareduced.proto.example.kanban.task.v1.ListTaskResponse)) {
      return super.equals(obj);
    }
    com.betareduced.proto.example.kanban.task.v1.ListTaskResponse other = (com.betareduced.proto.example.kanban.task.v1.ListTaskResponse) obj;

    if (!getContentList()
        .equals(other.getContentList())) return false;
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getContentCount() > 0) {
      hash = (37 * hash) + CONTENT_FIELD_NUMBER;
      hash = (53 * hash) + getContentList().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.betareduced.proto.example.kanban.task.v1.ListTaskResponse parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.betareduced.proto.example.kanban.task.v1.ListTaskResponse parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.betareduced.proto.example.kanban.task.v1.ListTaskResponse parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.betareduced.proto.example.kanban.task.v1.ListTaskResponse parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.betareduced.proto.example.kanban.task.v1.ListTaskResponse parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.betareduced.proto.example.kanban.task.v1.ListTaskResponse parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.betareduced.proto.example.kanban.task.v1.ListTaskResponse parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.betareduced.proto.example.kanban.task.v1.ListTaskResponse parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.betareduced.proto.example.kanban.task.v1.ListTaskResponse parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.betareduced.proto.example.kanban.task.v1.ListTaskResponse parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.betareduced.proto.example.kanban.task.v1.ListTaskResponse parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.betareduced.proto.example.kanban.task.v1.ListTaskResponse parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.betareduced.proto.example.kanban.task.v1.ListTaskResponse prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code example.kanban.task.v1.ListTaskResponse}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:example.kanban.task.v1.ListTaskResponse)
      com.betareduced.proto.example.kanban.task.v1.ListTaskResponseOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.betareduced.proto.example.kanban.task.v1.TaskOuterClass.internal_static_example_kanban_task_v1_ListTaskResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.betareduced.proto.example.kanban.task.v1.TaskOuterClass.internal_static_example_kanban_task_v1_ListTaskResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.betareduced.proto.example.kanban.task.v1.ListTaskResponse.class, com.betareduced.proto.example.kanban.task.v1.ListTaskResponse.Builder.class);
    }

    // Construct using com.betareduced.proto.example.kanban.task.v1.ListTaskResponse.newBuilder()
    private Builder() {

    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);

    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      if (contentBuilder_ == null) {
        content_ = java.util.Collections.emptyList();
      } else {
        content_ = null;
        contentBuilder_.clear();
      }
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.betareduced.proto.example.kanban.task.v1.TaskOuterClass.internal_static_example_kanban_task_v1_ListTaskResponse_descriptor;
    }

    @java.lang.Override
    public com.betareduced.proto.example.kanban.task.v1.ListTaskResponse getDefaultInstanceForType() {
      return com.betareduced.proto.example.kanban.task.v1.ListTaskResponse.getDefaultInstance();
    }

    @java.lang.Override
    public com.betareduced.proto.example.kanban.task.v1.ListTaskResponse build() {
      com.betareduced.proto.example.kanban.task.v1.ListTaskResponse result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.betareduced.proto.example.kanban.task.v1.ListTaskResponse buildPartial() {
      com.betareduced.proto.example.kanban.task.v1.ListTaskResponse result = new com.betareduced.proto.example.kanban.task.v1.ListTaskResponse(this);
      buildPartialRepeatedFields(result);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartialRepeatedFields(com.betareduced.proto.example.kanban.task.v1.ListTaskResponse result) {
      if (contentBuilder_ == null) {
        if (((bitField0_ & 0x00000001) != 0)) {
          content_ = java.util.Collections.unmodifiableList(content_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.content_ = content_;
      } else {
        result.content_ = contentBuilder_.build();
      }
    }

    private void buildPartial0(com.betareduced.proto.example.kanban.task.v1.ListTaskResponse result) {
      int from_bitField0_ = bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.betareduced.proto.example.kanban.task.v1.ListTaskResponse) {
        return mergeFrom((com.betareduced.proto.example.kanban.task.v1.ListTaskResponse)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.betareduced.proto.example.kanban.task.v1.ListTaskResponse other) {
      if (other == com.betareduced.proto.example.kanban.task.v1.ListTaskResponse.getDefaultInstance()) return this;
      if (contentBuilder_ == null) {
        if (!other.content_.isEmpty()) {
          if (content_.isEmpty()) {
            content_ = other.content_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensureContentIsMutable();
            content_.addAll(other.content_);
          }
          onChanged();
        }
      } else {
        if (!other.content_.isEmpty()) {
          if (contentBuilder_.isEmpty()) {
            contentBuilder_.dispose();
            contentBuilder_ = null;
            content_ = other.content_;
            bitField0_ = (bitField0_ & ~0x00000001);
            contentBuilder_ = 
              com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                 internalGetContentFieldBuilder() : null;
          } else {
            contentBuilder_.addAllMessages(other.content_);
          }
        }
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              com.betareduced.proto.example.kanban.task.v1.Task m =
                  input.readMessage(
                      com.betareduced.proto.example.kanban.task.v1.Task.parser(),
                      extensionRegistry);
              if (contentBuilder_ == null) {
                ensureContentIsMutable();
                content_.add(m);
              } else {
                contentBuilder_.addMessage(m);
              }
              break;
            } // case 10
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.util.List<com.betareduced.proto.example.kanban.task.v1.Task> content_ =
      java.util.Collections.emptyList();
    private void ensureContentIsMutable() {
      if (!((bitField0_ & 0x00000001) != 0)) {
        content_ = new java.util.ArrayList<com.betareduced.proto.example.kanban.task.v1.Task>(content_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilder<
        com.betareduced.proto.example.kanban.task.v1.Task, com.betareduced.proto.example.kanban.task.v1.Task.Builder, com.betareduced.proto.example.kanban.task.v1.TaskOrBuilder> contentBuilder_;

    /**
     * <code>repeated .example.kanban.task.v1.Task content = 1 [json_name = "content"];</code>
     */
    public java.util.List<com.betareduced.proto.example.kanban.task.v1.Task> getContentList() {
      if (contentBuilder_ == null) {
        return java.util.Collections.unmodifiableList(content_);
      } else {
        return contentBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .example.kanban.task.v1.Task content = 1 [json_name = "content"];</code>
     */
    public int getContentCount() {
      if (contentBuilder_ == null) {
        return content_.size();
      } else {
        return contentBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .example.kanban.task.v1.Task content = 1 [json_name = "content"];</code>
     */
    public com.betareduced.proto.example.kanban.task.v1.Task getContent(int index) {
      if (contentBuilder_ == null) {
        return content_.get(index);
      } else {
        return contentBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .example.kanban.task.v1.Task content = 1 [json_name = "content"];</code>
     */
    public Builder setContent(
        int index, com.betareduced.proto.example.kanban.task.v1.Task value) {
      if (contentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureContentIsMutable();
        content_.set(index, value);
        onChanged();
      } else {
        contentBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .example.kanban.task.v1.Task content = 1 [json_name = "content"];</code>
     */
    public Builder setContent(
        int index, com.betareduced.proto.example.kanban.task.v1.Task.Builder builderForValue) {
      if (contentBuilder_ == null) {
        ensureContentIsMutable();
        content_.set(index, builderForValue.build());
        onChanged();
      } else {
        contentBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .example.kanban.task.v1.Task content = 1 [json_name = "content"];</code>
     */
    public Builder addContent(com.betareduced.proto.example.kanban.task.v1.Task value) {
      if (contentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureContentIsMutable();
        content_.add(value);
        onChanged();
      } else {
        contentBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .example.kanban.task.v1.Task content = 1 [json_name = "content"];</code>
     */
    public Builder addContent(
        int index, com.betareduced.proto.example.kanban.task.v1.Task value) {
      if (contentBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensureContentIsMutable();
        content_.add(index, value);
        onChanged();
      } else {
        contentBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .example.kanban.task.v1.Task content = 1 [json_name = "content"];</code>
     */
    public Builder addContent(
        com.betareduced.proto.example.kanban.task.v1.Task.Builder builderForValue) {
      if (contentBuilder_ == null) {
        ensureContentIsMutable();
        content_.add(builderForValue.build());
        onChanged();
      } else {
        contentBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .example.kanban.task.v1.Task content = 1 [json_name = "content"];</code>
     */
    public Builder addContent(
        int index, com.betareduced.proto.example.kanban.task.v1.Task.Builder builderForValue) {
      if (contentBuilder_ == null) {
        ensureContentIsMutable();
        content_.add(index, builderForValue.build());
        onChanged();
      } else {
        contentBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .example.kanban.task.v1.Task content = 1 [json_name = "content"];</code>
     */
    public Builder addAllContent(
        java.lang.Iterable<? extends com.betareduced.proto.example.kanban.task.v1.Task> values) {
      if (contentBuilder_ == null) {
        ensureContentIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, content_);
        onChanged();
      } else {
        contentBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .example.kanban.task.v1.Task content = 1 [json_name = "content"];</code>
     */
    public Builder clearContent() {
      if (contentBuilder_ == null) {
        content_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        contentBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .example.kanban.task.v1.Task content = 1 [json_name = "content"];</code>
     */
    public Builder removeContent(int index) {
      if (contentBuilder_ == null) {
        ensureContentIsMutable();
        content_.remove(index);
        onChanged();
      } else {
        contentBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .example.kanban.task.v1.Task content = 1 [json_name = "content"];</code>
     */
    public com.betareduced.proto.example.kanban.task.v1.Task.Builder getContentBuilder(
        int index) {
      return internalGetContentFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .example.kanban.task.v1.Task content = 1 [json_name = "content"];</code>
     */
    public com.betareduced.proto.example.kanban.task.v1.TaskOrBuilder getContentOrBuilder(
        int index) {
      if (contentBuilder_ == null) {
        return content_.get(index);  } else {
        return contentBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .example.kanban.task.v1.Task content = 1 [json_name = "content"];</code>
     */
    public java.util.List<? extends com.betareduced.proto.example.kanban.task.v1.TaskOrBuilder> 
         getContentOrBuilderList() {
      if (contentBuilder_ != null) {
        return contentBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(content_);
      }
    }
    /**
     * <code>repeated .example.kanban.task.v1.Task content = 1 [json_name = "content"];</code>
     */
    public com.betareduced.proto.example.kanban.task.v1.Task.Builder addContentBuilder() {
      return internalGetContentFieldBuilder().addBuilder(
          com.betareduced.proto.example.kanban.task.v1.Task.getDefaultInstance());
    }
    /**
     * <code>repeated .example.kanban.task.v1.Task content = 1 [json_name = "content"];</code>
     */
    public com.betareduced.proto.example.kanban.task.v1.Task.Builder addContentBuilder(
        int index) {
      return internalGetContentFieldBuilder().addBuilder(
          index, com.betareduced.proto.example.kanban.task.v1.Task.getDefaultInstance());
    }
    /**
     * <code>repeated .example.kanban.task.v1.Task content = 1 [json_name = "content"];</code>
     */
    public java.util.List<com.betareduced.proto.example.kanban.task.v1.Task.Builder> 
         getContentBuilderList() {
      return internalGetContentFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilder<
        com.betareduced.proto.example.kanban.task.v1.Task, com.betareduced.proto.example.kanban.task.v1.Task.Builder, com.betareduced.proto.example.kanban.task.v1.TaskOrBuilder> 
        internalGetContentFieldBuilder() {
      if (contentBuilder_ == null) {
        contentBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
            com.betareduced.proto.example.kanban.task.v1.Task, com.betareduced.proto.example.kanban.task.v1.Task.Builder, com.betareduced.proto.example.kanban.task.v1.TaskOrBuilder>(
                content_,
                ((bitField0_ & 0x00000001) != 0),
                getParentForChildren(),
                isClean());
        content_ = null;
      }
      return contentBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:example.kanban.task.v1.ListTaskResponse)
  }

  // @@protoc_insertion_point(class_scope:example.kanban.task.v1.ListTaskResponse)
  private static final com.betareduced.proto.example.kanban.task.v1.ListTaskResponse DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.betareduced.proto.example.kanban.task.v1.ListTaskResponse();
  }

  public static com.betareduced.proto.example.kanban.task.v1.ListTaskResponse getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<ListTaskResponse>
      PARSER = new com.google.protobuf.AbstractParser<ListTaskResponse>() {
    @java.lang.Override
    public ListTaskResponse parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<ListTaskResponse> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<ListTaskResponse> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.betareduced.proto.example.kanban.task.v1.ListTaskResponse getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

