// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: example/kanban/task/v1/task.proto
// Protobuf Java Version: 4.34.1

package com.betareduced.proto.example.kanban.task.v1;

@com.google.protobuf.Generated
public interface ListTaskResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:example.kanban.task.v1.ListTaskResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .example.kanban.task.v1.Task content = 1 [json_name = "content"];</code>
   */
  java.util.List<com.betareduced.proto.example.kanban.task.v1.Task> 
      getContentList();
  /**
   * <code>repeated .example.kanban.task.v1.Task content = 1 [json_name = "content"];</code>
   */
  com.betareduced.proto.example.kanban.task.v1.Task getContent(int index);
  /**
   * <code>repeated .example.kanban.task.v1.Task content = 1 [json_name = "content"];</code>
   */
  int getContentCount();
  /**
   * <code>repeated .example.kanban.task.v1.Task content = 1 [json_name = "content"];</code>
   */
  java.util.List<? extends com.betareduced.proto.example.kanban.task.v1.TaskOrBuilder> 
      getContentOrBuilderList();
  /**
   * <code>repeated .example.kanban.task.v1.Task content = 1 [json_name = "content"];</code>
   */
  com.betareduced.proto.example.kanban.task.v1.TaskOrBuilder getContentOrBuilder(
      int index);
}
