// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: example/kanban/task/v1/task.proto
// Protobuf Java Version: 4.34.1

package com.betareduced.proto.example.kanban.task.v1;

@com.google.protobuf.Generated
public interface ListTaskRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:example.kanban.task.v1.ListTaskRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.example.kanban.task.v1.ListTaskRequest.Filter f = 1 [json_name = "f"];</code>
   * @return Whether the f field is set.
   */
  boolean hasF();
  /**
   * <code>.example.kanban.task.v1.ListTaskRequest.Filter f = 1 [json_name = "f"];</code>
   * @return The f.
   */
  com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Filter getF();
  /**
   * <code>.example.kanban.task.v1.ListTaskRequest.Filter f = 1 [json_name = "f"];</code>
   */
  com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.FilterOrBuilder getFOrBuilder();

  /**
   * <code>.example.kanban.task.v1.ListTaskRequest.Sortkey sort_by = 2 [json_name = "sortBy"];</code>
   * @return Whether the sortBy field is set.
   */
  boolean hasSortBy();
  /**
   * <code>.example.kanban.task.v1.ListTaskRequest.Sortkey sort_by = 2 [json_name = "sortBy"];</code>
   * @return The enum numeric value on the wire for sortBy.
   */
  int getSortByValue();
  /**
   * <code>.example.kanban.task.v1.ListTaskRequest.Sortkey sort_by = 2 [json_name = "sortBy"];</code>
   * @return The sortBy.
   */
  com.betareduced.proto.example.kanban.task.v1.ListTaskRequest.Sortkey getSortBy();
}
