// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: example/kanban/task/v1/task.proto
// Protobuf Java Version: 4.34.1

package com.betareduced.proto.example.kanban.task.v1;

/**
 * Protobuf enum {@code example.kanban.task.v1.Status}
 */
@com.google.protobuf.Generated
public enum Status
    implements com.google.protobuf.ProtocolMessageEnum {
  /**
   * <code>BACKLOG = 0;</code>
   */
  BACKLOG(0),
  /**
   * <code>READY = 1;</code>
   */
  READY(1),
  /**
   * <code>DOING = 2;</code>
   */
  DOING(2),
  /**
   * <code>REVIEW = 3;</code>
   */
  REVIEW(3),
  /**
   * <code>DONE = 4;</code>
   */
  DONE(4),
  /**
   * <code>ARCHIVED = 5;</code>
   */
  ARCHIVED(5),
  UNRECOGNIZED(-1),
  ;

  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "Status");
  }
  /**
   * <code>BACKLOG = 0;</code>
   */
  public static final int BACKLOG_VALUE = 0;
  /**
   * <code>READY = 1;</code>
   */
  public static final int READY_VALUE = 1;
  /**
   * <code>DOING = 2;</code>
   */
  public static final int DOING_VALUE = 2;
  /**
   * <code>REVIEW = 3;</code>
   */
  public static final int REVIEW_VALUE = 3;
  /**
   * <code>DONE = 4;</code>
   */
  public static final int DONE_VALUE = 4;
  /**
   * <code>ARCHIVED = 5;</code>
   */
  public static final int ARCHIVED_VALUE = 5;


  public final int getNumber() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalArgumentException(
          "Can't get the number of an unknown enum value.");
    }
    return value;
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static Status valueOf(int value) {
    return forNumber(value);
  }

  /**
   * @param value The numeric wire value of the corresponding enum entry.
   * @return The enum associated with the given numeric wire value.
   */
  public static Status forNumber(int value) {
    switch (value) {
      case 0: return BACKLOG;
      case 1: return READY;
      case 2: return DOING;
      case 3: return REVIEW;
      case 4: return DONE;
      case 5: return ARCHIVED;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<Status>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      Status> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<Status>() {
          public Status findValueByNumber(int number) {
            return Status.forNumber(number);
          }
        };

  public final com.google.protobuf.Descriptors.EnumValueDescriptor
      getValueDescriptor() {
    if (this == UNRECOGNIZED) {
      throw new java.lang.IllegalStateException(
          "Can't get the descriptor of an unrecognized enum value.");
    }
    return getDescriptor().getValue(ordinal());
  }
  public final com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptorForType() {
    return getDescriptor();
  }
  public static com.google.protobuf.Descriptors.EnumDescriptor
      getDescriptor() {
    return com.betareduced.proto.example.kanban.task.v1.TaskOuterClass.getDescriptor().getEnumType(0);
  }

  private static final Status[] VALUES = values();

  public static Status valueOf(
      com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
    if (desc.getType() != getDescriptor()) {
      throw new java.lang.IllegalArgumentException(
        "EnumValueDescriptor is not for this type.");
    }
    if (desc.getIndex() == -1) {
      return UNRECOGNIZED;
    }
    return VALUES[desc.getIndex()];
  }

  private final int value;

  private Status(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:example.kanban.task.v1.Status)
}

