// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: example/kanban/task/v1/task.proto
// Protobuf Java Version: 4.34.1

package com.betareduced.proto.example.kanban.task.v1;

@com.google.protobuf.Generated
public final class TaskOuterClass extends com.google.protobuf.GeneratedFile {
  private TaskOuterClass() {}
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "TaskOuterClass");
  }
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_kanban_task_v1_Task_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_example_kanban_task_v1_Task_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_kanban_task_v1_CreateTaskRequest_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_example_kanban_task_v1_CreateTaskRequest_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_example_kanban_task_v1_CreateTaskResponse_descriptor;
  static final 
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_example_kanban_task_v1_CreateTaskResponse_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static final com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n!example/kanban/task/v1/task.proto\022\026exa" +
      "mple.kanban.task.v1\032%common/wkt/v1/recor" +
      "d_timestamps.proto\"\267\001\n\004Task\022\016\n\002id\030\001 \001(\tR" +
      "\002id\022\022\n\004name\030\002 \001(\tR\004name\022\022\n\004desc\030\003 \001(\tR\004d" +
      "esc\0226\n\006status\030\004 \001(\0162\036.example.kanban.tas" +
      "k.v1.StatusR\006status\022?\n\ntimestamps\030\005 \001(\0132" +
      "\037.common.wkt.v1.RecordTimestampsR\ntimest" +
      "amps\";\n\021CreateTaskRequest\022\022\n\004name\030\001 \001(\tR" +
      "\004name\022\022\n\004desc\030\002 \001(\tR\004desc\"F\n\022CreateTaskR" +
      "esponse\0220\n\004task\030\001 \001(\0132\034.example.kanban.t" +
      "ask.v1.TaskR\004task*O\n\006Status\022\013\n\007BACKLOG\020\000" +
      "\022\t\n\005READY\020\001\022\t\n\005DOING\020\002\022\n\n\006REVIEW\020\003\022\010\n\004DO" +
      "NE\020\004\022\014\n\010ARCHIVED\020\0052r\n\013TaskService\022c\n\nCre" +
      "ateTask\022).example.kanban.task.v1.CreateT" +
      "askRequest\032*.example.kanban.task.v1.Crea" +
      "teTaskResponseBo\n,com.betareduced.proto." +
      "example.kanban.task.v1P\001Z=github.com/bet" +
      "areduced/proto/go/example/kanban/task/v1" +
      ";taskpbb\010editionsp\350\007"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.betareduced.proto.common.wkt.v1.RecordTimestampsOuterClass.getDescriptor(),
        });
    internal_static_example_kanban_task_v1_Task_descriptor =
      getDescriptor().getMessageType(0);
    internal_static_example_kanban_task_v1_Task_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_example_kanban_task_v1_Task_descriptor,
        new java.lang.String[] { "Id", "Name", "Desc", "Status", "Timestamps", });
    internal_static_example_kanban_task_v1_CreateTaskRequest_descriptor =
      getDescriptor().getMessageType(1);
    internal_static_example_kanban_task_v1_CreateTaskRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_example_kanban_task_v1_CreateTaskRequest_descriptor,
        new java.lang.String[] { "Name", "Desc", });
    internal_static_example_kanban_task_v1_CreateTaskResponse_descriptor =
      getDescriptor().getMessageType(2);
    internal_static_example_kanban_task_v1_CreateTaskResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_example_kanban_task_v1_CreateTaskResponse_descriptor,
        new java.lang.String[] { "Task", });
    descriptor.resolveAllFeaturesImmutable();
    com.betareduced.proto.common.wkt.v1.RecordTimestampsOuterClass.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
