// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: example/kanban/task/v1/task.proto
// Protobuf Java Version: 4.34.1

package com.betareduced.proto.example.kanban.task.v1;

/**
 * Protobuf type {@code example.kanban.task.v1.Task}
 */
@com.google.protobuf.Generated
public final class Task extends
    com.google.protobuf.GeneratedMessage implements
    // @@protoc_insertion_point(message_implements:example.kanban.task.v1.Task)
    TaskOrBuilder {
private static final long serialVersionUID = 0L;
  static {
    com.google.protobuf.RuntimeVersion.validateProtobufGencodeVersion(
      com.google.protobuf.RuntimeVersion.RuntimeDomain.PUBLIC,
      /* major= */ 4,
      /* minor= */ 34,
      /* patch= */ 1,
      /* suffix= */ "",
      "Task");
  }
  // Use Task.newBuilder() to construct.
  private Task(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
    super(builder);
  }
  private Task() {
    id_ = "";
    name_ = "";
    desc_ = "";
    status_ = 0;
  }

  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return com.betareduced.proto.example.kanban.task.v1.TaskOuterClass.internal_static_example_kanban_task_v1_Task_descriptor;
  }

  @java.lang.Override
  public com.google.protobuf.Descriptors.Descriptor getDescriptorForType() {
    return com.betareduced.proto.example.kanban.task.v1.TaskOuterClass.internal_static_example_kanban_task_v1_Task_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return com.betareduced.proto.example.kanban.task.v1.TaskOuterClass.internal_static_example_kanban_task_v1_Task_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            com.betareduced.proto.example.kanban.task.v1.Task.class, com.betareduced.proto.example.kanban.task.v1.Task.Builder.class);
  }

  private int bitField0_;
  public static final int ID_FIELD_NUMBER = 1;
  @SuppressWarnings("serial")
  private volatile java.lang.Object id_ = "";
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return Whether the id field is set.
   */
  @java.lang.Override
  public boolean hasId() {
    return ((bitField0_ & 0x00000001) != 0);
  }
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The id.
   */
  @java.lang.Override
  public java.lang.String getId() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      id_ = s;
      return s;
    }
  }
  /**
   * <code>string id = 1 [json_name = "id"];</code>
   * @return The bytes for id.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getIdBytes() {
    java.lang.Object ref = id_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      id_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAME_FIELD_NUMBER = 2;
  @SuppressWarnings("serial")
  private volatile java.lang.Object name_ = "";
  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return Whether the name field is set.
   */
  @java.lang.Override
  public boolean hasName() {
    return ((bitField0_ & 0x00000002) != 0);
  }
  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The name.
   */
  @java.lang.Override
  public java.lang.String getName() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      name_ = s;
      return s;
    }
  }
  /**
   * <code>string name = 2 [json_name = "name"];</code>
   * @return The bytes for name.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getNameBytes() {
    java.lang.Object ref = name_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      name_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int DESC_FIELD_NUMBER = 3;
  @SuppressWarnings("serial")
  private volatile java.lang.Object desc_ = "";
  /**
   * <code>string desc = 3 [json_name = "desc"];</code>
   * @return Whether the desc field is set.
   */
  @java.lang.Override
  public boolean hasDesc() {
    return ((bitField0_ & 0x00000004) != 0);
  }
  /**
   * <code>string desc = 3 [json_name = "desc"];</code>
   * @return The desc.
   */
  @java.lang.Override
  public java.lang.String getDesc() {
    java.lang.Object ref = desc_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      desc_ = s;
      return s;
    }
  }
  /**
   * <code>string desc = 3 [json_name = "desc"];</code>
   * @return The bytes for desc.
   */
  @java.lang.Override
  public com.google.protobuf.ByteString
      getDescBytes() {
    java.lang.Object ref = desc_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      desc_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int STATUS_FIELD_NUMBER = 4;
  private int status_ = 0;
  /**
   * <code>.example.kanban.task.v1.Status status = 4 [json_name = "status"];</code>
   * @return Whether the status field is set.
   */
  @java.lang.Override public boolean hasStatus() {
    return ((bitField0_ & 0x00000008) != 0);
  }
  /**
   * <code>.example.kanban.task.v1.Status status = 4 [json_name = "status"];</code>
   * @return The enum numeric value on the wire for status.
   */
  @java.lang.Override public int getStatusValue() {
    return status_;
  }
  /**
   * <code>.example.kanban.task.v1.Status status = 4 [json_name = "status"];</code>
   * @return The status.
   */
  @java.lang.Override public com.betareduced.proto.example.kanban.task.v1.Status getStatus() {
    com.betareduced.proto.example.kanban.task.v1.Status result = com.betareduced.proto.example.kanban.task.v1.Status.forNumber(status_);
    return result == null ? com.betareduced.proto.example.kanban.task.v1.Status.UNRECOGNIZED : result;
  }

  public static final int TIMESTAMPS_FIELD_NUMBER = 5;
  private com.betareduced.proto.common.wkt.v1.RecordTimestamps timestamps_;
  /**
   * <code>.common.wkt.v1.RecordTimestamps timestamps = 5 [json_name = "timestamps"];</code>
   * @return Whether the timestamps field is set.
   */
  @java.lang.Override
  public boolean hasTimestamps() {
    return ((bitField0_ & 0x00000010) != 0);
  }
  /**
   * <code>.common.wkt.v1.RecordTimestamps timestamps = 5 [json_name = "timestamps"];</code>
   * @return The timestamps.
   */
  @java.lang.Override
  public com.betareduced.proto.common.wkt.v1.RecordTimestamps getTimestamps() {
    return timestamps_ == null ? com.betareduced.proto.common.wkt.v1.RecordTimestamps.getDefaultInstance() : timestamps_;
  }
  /**
   * <code>.common.wkt.v1.RecordTimestamps timestamps = 5 [json_name = "timestamps"];</code>
   */
  @java.lang.Override
  public com.betareduced.proto.common.wkt.v1.RecordTimestampsOrBuilder getTimestampsOrBuilder() {
    return timestamps_ == null ? com.betareduced.proto.common.wkt.v1.RecordTimestamps.getDefaultInstance() : timestamps_;
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (((bitField0_ & 0x00000001) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 1, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 2, name_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      com.google.protobuf.GeneratedMessage.writeString(output, 3, desc_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      output.writeEnum(4, status_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      output.writeMessage(5, getTimestamps());
    }
    getUnknownFields().writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (((bitField0_ & 0x00000001) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(1, id_);
    }
    if (((bitField0_ & 0x00000002) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(2, name_);
    }
    if (((bitField0_ & 0x00000004) != 0)) {
      size += com.google.protobuf.GeneratedMessage.computeStringSize(3, desc_);
    }
    if (((bitField0_ & 0x00000008) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(4, status_);
    }
    if (((bitField0_ & 0x00000010) != 0)) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(5, getTimestamps());
    }
    size += getUnknownFields().getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof com.betareduced.proto.example.kanban.task.v1.Task)) {
      return super.equals(obj);
    }
    com.betareduced.proto.example.kanban.task.v1.Task other = (com.betareduced.proto.example.kanban.task.v1.Task) obj;

    if (hasId() != other.hasId()) return false;
    if (hasId()) {
      if (!getId()
          .equals(other.getId())) return false;
    }
    if (hasName() != other.hasName()) return false;
    if (hasName()) {
      if (!getName()
          .equals(other.getName())) return false;
    }
    if (hasDesc() != other.hasDesc()) return false;
    if (hasDesc()) {
      if (!getDesc()
          .equals(other.getDesc())) return false;
    }
    if (hasStatus() != other.hasStatus()) return false;
    if (hasStatus()) {
      if (status_ != other.status_) return false;
    }
    if (hasTimestamps() != other.hasTimestamps()) return false;
    if (hasTimestamps()) {
      if (!getTimestamps()
          .equals(other.getTimestamps())) return false;
    }
    if (!getUnknownFields().equals(other.getUnknownFields())) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasId()) {
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
    }
    if (hasName()) {
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
    }
    if (hasDesc()) {
      hash = (37 * hash) + DESC_FIELD_NUMBER;
      hash = (53 * hash) + getDesc().hashCode();
    }
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + status_;
    }
    if (hasTimestamps()) {
      hash = (37 * hash) + TIMESTAMPS_FIELD_NUMBER;
      hash = (53 * hash) + getTimestamps().hashCode();
    }
    hash = (29 * hash) + getUnknownFields().hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static com.betareduced.proto.example.kanban.task.v1.Task parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.betareduced.proto.example.kanban.task.v1.Task parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.betareduced.proto.example.kanban.task.v1.Task parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.betareduced.proto.example.kanban.task.v1.Task parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.betareduced.proto.example.kanban.task.v1.Task parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static com.betareduced.proto.example.kanban.task.v1.Task parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static com.betareduced.proto.example.kanban.task.v1.Task parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.betareduced.proto.example.kanban.task.v1.Task parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public static com.betareduced.proto.example.kanban.task.v1.Task parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input);
  }

  public static com.betareduced.proto.example.kanban.task.v1.Task parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static com.betareduced.proto.example.kanban.task.v1.Task parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input);
  }
  public static com.betareduced.proto.example.kanban.task.v1.Task parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessage
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(com.betareduced.proto.example.kanban.task.v1.Task prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessage.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code example.kanban.task.v1.Task}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessage.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:example.kanban.task.v1.Task)
      com.betareduced.proto.example.kanban.task.v1.TaskOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.betareduced.proto.example.kanban.task.v1.TaskOuterClass.internal_static_example_kanban_task_v1_Task_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.betareduced.proto.example.kanban.task.v1.TaskOuterClass.internal_static_example_kanban_task_v1_Task_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.betareduced.proto.example.kanban.task.v1.Task.class, com.betareduced.proto.example.kanban.task.v1.Task.Builder.class);
    }

    // Construct using com.betareduced.proto.example.kanban.task.v1.Task.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessage
              .alwaysUseFieldBuilders) {
        internalGetTimestampsFieldBuilder();
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      bitField0_ = 0;
      id_ = "";
      name_ = "";
      desc_ = "";
      status_ = 0;
      timestamps_ = null;
      if (timestampsBuilder_ != null) {
        timestampsBuilder_.dispose();
        timestampsBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return com.betareduced.proto.example.kanban.task.v1.TaskOuterClass.internal_static_example_kanban_task_v1_Task_descriptor;
    }

    @java.lang.Override
    public com.betareduced.proto.example.kanban.task.v1.Task getDefaultInstanceForType() {
      return com.betareduced.proto.example.kanban.task.v1.Task.getDefaultInstance();
    }

    @java.lang.Override
    public com.betareduced.proto.example.kanban.task.v1.Task build() {
      com.betareduced.proto.example.kanban.task.v1.Task result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public com.betareduced.proto.example.kanban.task.v1.Task buildPartial() {
      com.betareduced.proto.example.kanban.task.v1.Task result = new com.betareduced.proto.example.kanban.task.v1.Task(this);
      if (bitField0_ != 0) { buildPartial0(result); }
      onBuilt();
      return result;
    }

    private void buildPartial0(com.betareduced.proto.example.kanban.task.v1.Task result) {
      int from_bitField0_ = bitField0_;
      int to_bitField0_ = 0;
      if (((from_bitField0_ & 0x00000001) != 0)) {
        result.id_ = id_;
        to_bitField0_ |= 0x00000001;
      }
      if (((from_bitField0_ & 0x00000002) != 0)) {
        result.name_ = name_;
        to_bitField0_ |= 0x00000002;
      }
      if (((from_bitField0_ & 0x00000004) != 0)) {
        result.desc_ = desc_;
        to_bitField0_ |= 0x00000004;
      }
      if (((from_bitField0_ & 0x00000008) != 0)) {
        result.status_ = status_;
        to_bitField0_ |= 0x00000008;
      }
      if (((from_bitField0_ & 0x00000010) != 0)) {
        result.timestamps_ = timestampsBuilder_ == null
            ? timestamps_
            : timestampsBuilder_.build();
        to_bitField0_ |= 0x00000010;
      }
      result.bitField0_ |= to_bitField0_;
    }

    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof com.betareduced.proto.example.kanban.task.v1.Task) {
        return mergeFrom((com.betareduced.proto.example.kanban.task.v1.Task)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(com.betareduced.proto.example.kanban.task.v1.Task other) {
      if (other == com.betareduced.proto.example.kanban.task.v1.Task.getDefaultInstance()) return this;
      if (other.hasId()) {
        id_ = other.id_;
        bitField0_ |= 0x00000001;
        onChanged();
      }
      if (other.hasName()) {
        name_ = other.name_;
        bitField0_ |= 0x00000002;
        onChanged();
      }
      if (other.hasDesc()) {
        desc_ = other.desc_;
        bitField0_ |= 0x00000004;
        onChanged();
      }
      if (other.hasStatus()) {
        setStatusValue(other.getStatusValue());
      }
      if (other.hasTimestamps()) {
        mergeTimestamps(other.getTimestamps());
      }
      this.mergeUnknownFields(other.getUnknownFields());
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              id_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000001;
              break;
            } // case 10
            case 18: {
              name_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000002;
              break;
            } // case 18
            case 26: {
              desc_ = input.readStringRequireUtf8();
              bitField0_ |= 0x00000004;
              break;
            } // case 26
            case 32: {
              status_ = input.readEnum();
              bitField0_ |= 0x00000008;
              break;
            } // case 32
            case 42: {
              input.readMessage(
                  internalGetTimestampsFieldBuilder().getBuilder(),
                  extensionRegistry);
              bitField0_ |= 0x00000010;
              break;
            } // case 42
            default: {
              if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                done = true; // was an endgroup tag
              }
              break;
            } // default:
          } // switch (tag)
        } // while (!done)
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.unwrapIOException();
      } finally {
        onChanged();
      } // finally
      return this;
    }
    private int bitField0_;

    private java.lang.Object id_ = "";
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return Whether the id field is set.
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) != 0);
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The id to set.
     * @return This builder for chaining.
     */
    public Builder setId(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @return This builder for chaining.
     */
    public Builder clearId() {
      id_ = getDefaultInstance().getId();
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>string id = 1 [json_name = "id"];</code>
     * @param value The bytes for id to set.
     * @return This builder for chaining.
     */
    public Builder setIdBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      id_ = value;
      bitField0_ |= 0x00000001;
      onChanged();
      return this;
    }

    private java.lang.Object name_ = "";
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return Whether the name field is set.
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000002) != 0);
    }
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @param value The name to set.
     * @return This builder for chaining.
     */
    public Builder setName(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @return This builder for chaining.
     */
    public Builder clearName() {
      name_ = getDefaultInstance().getName();
      bitField0_ = (bitField0_ & ~0x00000002);
      onChanged();
      return this;
    }
    /**
     * <code>string name = 2 [json_name = "name"];</code>
     * @param value The bytes for name to set.
     * @return This builder for chaining.
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      name_ = value;
      bitField0_ |= 0x00000002;
      onChanged();
      return this;
    }

    private java.lang.Object desc_ = "";
    /**
     * <code>string desc = 3 [json_name = "desc"];</code>
     * @return Whether the desc field is set.
     */
    public boolean hasDesc() {
      return ((bitField0_ & 0x00000004) != 0);
    }
    /**
     * <code>string desc = 3 [json_name = "desc"];</code>
     * @return The desc.
     */
    public java.lang.String getDesc() {
      java.lang.Object ref = desc_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        desc_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string desc = 3 [json_name = "desc"];</code>
     * @return The bytes for desc.
     */
    public com.google.protobuf.ByteString
        getDescBytes() {
      java.lang.Object ref = desc_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        desc_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string desc = 3 [json_name = "desc"];</code>
     * @param value The desc to set.
     * @return This builder for chaining.
     */
    public Builder setDesc(
        java.lang.String value) {
      if (value == null) { throw new NullPointerException(); }
      desc_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }
    /**
     * <code>string desc = 3 [json_name = "desc"];</code>
     * @return This builder for chaining.
     */
    public Builder clearDesc() {
      desc_ = getDefaultInstance().getDesc();
      bitField0_ = (bitField0_ & ~0x00000004);
      onChanged();
      return this;
    }
    /**
     * <code>string desc = 3 [json_name = "desc"];</code>
     * @param value The bytes for desc to set.
     * @return This builder for chaining.
     */
    public Builder setDescBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) { throw new NullPointerException(); }
      checkByteStringIsUtf8(value);
      desc_ = value;
      bitField0_ |= 0x00000004;
      onChanged();
      return this;
    }

    private int status_ = 0;
    /**
     * <code>.example.kanban.task.v1.Status status = 4 [json_name = "status"];</code>
     * @return Whether the status field is set.
     */
    @java.lang.Override public boolean hasStatus() {
      return ((bitField0_ & 0x00000008) != 0);
    }
    /**
     * <code>.example.kanban.task.v1.Status status = 4 [json_name = "status"];</code>
     * @return The enum numeric value on the wire for status.
     */
    @java.lang.Override public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.example.kanban.task.v1.Status status = 4 [json_name = "status"];</code>
     * @param value The enum numeric value on the wire for status to set.
     * @throws IllegalArgumentException if UNRECOGNIZED is provided.
     * @return This builder for chaining.
     */
    public Builder setStatusValue(int value) {
      status_ = value;
      bitField0_ |= 0x00000008;
      onChanged();
      return this;
    }
    /**
     * <code>.example.kanban.task.v1.Status status = 4 [json_name = "status"];</code>
     * @return The status.
     */
    @java.lang.Override
    public com.betareduced.proto.example.kanban.task.v1.Status getStatus() {
      com.betareduced.proto.example.kanban.task.v1.Status result = com.betareduced.proto.example.kanban.task.v1.Status.forNumber(status_);
      return result == null ? com.betareduced.proto.example.kanban.task.v1.Status.UNRECOGNIZED : result;
    }
    /**
     * <code>.example.kanban.task.v1.Status status = 4 [json_name = "status"];</code>
     * @param value The status to set.
     * @return This builder for chaining.
     */
    public Builder setStatus(com.betareduced.proto.example.kanban.task.v1.Status value) {
      if (value == null) { throw new NullPointerException(); }
      bitField0_ |= 0x00000008;
      status_ = value.getNumber();
      onChanged();
      return this;
    }
    /**
     * <code>.example.kanban.task.v1.Status status = 4 [json_name = "status"];</code>
     * @return This builder for chaining.
     */
    public Builder clearStatus() {
      bitField0_ = (bitField0_ & ~0x00000008);
      status_ = 0;
      onChanged();
      return this;
    }

    private com.betareduced.proto.common.wkt.v1.RecordTimestamps timestamps_;
    private com.google.protobuf.SingleFieldBuilder<
        com.betareduced.proto.common.wkt.v1.RecordTimestamps, com.betareduced.proto.common.wkt.v1.RecordTimestamps.Builder, com.betareduced.proto.common.wkt.v1.RecordTimestampsOrBuilder> timestampsBuilder_;
    /**
     * <code>.common.wkt.v1.RecordTimestamps timestamps = 5 [json_name = "timestamps"];</code>
     * @return Whether the timestamps field is set.
     */
    public boolean hasTimestamps() {
      return ((bitField0_ & 0x00000010) != 0);
    }
    /**
     * <code>.common.wkt.v1.RecordTimestamps timestamps = 5 [json_name = "timestamps"];</code>
     * @return The timestamps.
     */
    public com.betareduced.proto.common.wkt.v1.RecordTimestamps getTimestamps() {
      if (timestampsBuilder_ == null) {
        return timestamps_ == null ? com.betareduced.proto.common.wkt.v1.RecordTimestamps.getDefaultInstance() : timestamps_;
      } else {
        return timestampsBuilder_.getMessage();
      }
    }
    /**
     * <code>.common.wkt.v1.RecordTimestamps timestamps = 5 [json_name = "timestamps"];</code>
     */
    public Builder setTimestamps(com.betareduced.proto.common.wkt.v1.RecordTimestamps value) {
      if (timestampsBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        timestamps_ = value;
      } else {
        timestampsBuilder_.setMessage(value);
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.common.wkt.v1.RecordTimestamps timestamps = 5 [json_name = "timestamps"];</code>
     */
    public Builder setTimestamps(
        com.betareduced.proto.common.wkt.v1.RecordTimestamps.Builder builderForValue) {
      if (timestampsBuilder_ == null) {
        timestamps_ = builderForValue.build();
      } else {
        timestampsBuilder_.setMessage(builderForValue.build());
      }
      bitField0_ |= 0x00000010;
      onChanged();
      return this;
    }
    /**
     * <code>.common.wkt.v1.RecordTimestamps timestamps = 5 [json_name = "timestamps"];</code>
     */
    public Builder mergeTimestamps(com.betareduced.proto.common.wkt.v1.RecordTimestamps value) {
      if (timestampsBuilder_ == null) {
        if (((bitField0_ & 0x00000010) != 0) &&
          timestamps_ != null &&
          timestamps_ != com.betareduced.proto.common.wkt.v1.RecordTimestamps.getDefaultInstance()) {
          getTimestampsBuilder().mergeFrom(value);
        } else {
          timestamps_ = value;
        }
      } else {
        timestampsBuilder_.mergeFrom(value);
      }
      if (timestamps_ != null) {
        bitField0_ |= 0x00000010;
        onChanged();
      }
      return this;
    }
    /**
     * <code>.common.wkt.v1.RecordTimestamps timestamps = 5 [json_name = "timestamps"];</code>
     */
    public Builder clearTimestamps() {
      bitField0_ = (bitField0_ & ~0x00000010);
      timestamps_ = null;
      if (timestampsBuilder_ != null) {
        timestampsBuilder_.dispose();
        timestampsBuilder_ = null;
      }
      onChanged();
      return this;
    }
    /**
     * <code>.common.wkt.v1.RecordTimestamps timestamps = 5 [json_name = "timestamps"];</code>
     */
    public com.betareduced.proto.common.wkt.v1.RecordTimestamps.Builder getTimestampsBuilder() {
      bitField0_ |= 0x00000010;
      onChanged();
      return internalGetTimestampsFieldBuilder().getBuilder();
    }
    /**
     * <code>.common.wkt.v1.RecordTimestamps timestamps = 5 [json_name = "timestamps"];</code>
     */
    public com.betareduced.proto.common.wkt.v1.RecordTimestampsOrBuilder getTimestampsOrBuilder() {
      if (timestampsBuilder_ != null) {
        return timestampsBuilder_.getMessageOrBuilder();
      } else {
        return timestamps_ == null ?
            com.betareduced.proto.common.wkt.v1.RecordTimestamps.getDefaultInstance() : timestamps_;
      }
    }
    /**
     * <code>.common.wkt.v1.RecordTimestamps timestamps = 5 [json_name = "timestamps"];</code>
     */
    private com.google.protobuf.SingleFieldBuilder<
        com.betareduced.proto.common.wkt.v1.RecordTimestamps, com.betareduced.proto.common.wkt.v1.RecordTimestamps.Builder, com.betareduced.proto.common.wkt.v1.RecordTimestampsOrBuilder> 
        internalGetTimestampsFieldBuilder() {
      if (timestampsBuilder_ == null) {
        timestampsBuilder_ = new com.google.protobuf.SingleFieldBuilder<
            com.betareduced.proto.common.wkt.v1.RecordTimestamps, com.betareduced.proto.common.wkt.v1.RecordTimestamps.Builder, com.betareduced.proto.common.wkt.v1.RecordTimestampsOrBuilder>(
                getTimestamps(),
                getParentForChildren(),
                isClean());
        timestamps_ = null;
      }
      return timestampsBuilder_;
    }

    // @@protoc_insertion_point(builder_scope:example.kanban.task.v1.Task)
  }

  // @@protoc_insertion_point(class_scope:example.kanban.task.v1.Task)
  private static final com.betareduced.proto.example.kanban.task.v1.Task DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new com.betareduced.proto.example.kanban.task.v1.Task();
  }

  public static com.betareduced.proto.example.kanban.task.v1.Task getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Task>
      PARSER = new com.google.protobuf.AbstractParser<Task>() {
    @java.lang.Override
    public Task parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      Builder builder = newBuilder();
      try {
        builder.mergeFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(builder.buildPartial());
      } catch (com.google.protobuf.UninitializedMessageException e) {
        throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(e)
            .setUnfinishedMessage(builder.buildPartial());
      }
      return builder.buildPartial();
    }
  };

  public static com.google.protobuf.Parser<Task> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Task> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public com.betareduced.proto.example.kanban.task.v1.Task getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

